const fs = require('fs');

const data = {
  "compras": {
    level1: {
      textEn: "I absolutely love shopping for new clothes and updating my wardrobe every season. Usually, I prefer to go to the large mall on Saturday mornings right after breakfast because it is very quiet and not crowded. Last week, while walking past my favorite store, I found a beautiful, stylish jacket on display. However, when I checked the price tag, I realized it was way too expensive for my current budget. So, I decided to be practical and buy a cheaper casual shirt and a pair of comfortable blue jeans instead. Saving money is very important to me, so I always look carefully for great discounts and seasonal sales before I buy anything.",
      textPt: "Eu absolutamente amo comprar roupas novas e atualizar meu guarda-roupa a cada estação. Geralmente, prefiro ir ao grande shopping nas manhãs de sábado, logo após o café da manhã, porque é muito tranquilo e não está lotado. Na semana passada, ao passar pela minha loja favorita, encontrei uma jaqueta linda e estilosa em exibição. No entanto, quando verifiquei a etiqueta de preço, percebi que era muito cara para o meu orçamento atual. Então, decidi ser prático e comprar uma camisa casual mais barata e uma calça jeans azul confortável. Economizar dinheiro é muito importante para mim, então sempre procuro cuidadosamente por ótimos descontos e promoções sazonais antes de comprar qualquer coisa.",
      questions: [
        { question: "Why does the author prefer to go to the mall on Saturday mornings?", options: ["Because the mall is quiet", "Because that is when new clothes arrive", "Because they work on Saturday afternoons", "Because the discounts are better"], correctIndex: 0, explanation: "They go on Saturday mornings 'because it is very quiet and not crowded'." },
        { question: "Why didn't the author buy the jacket?", options: ["It was too expensive", "It was the wrong color", "It did not fit well", "They preferred the shirt"], correctIndex: 0, explanation: "They didn't buy the jacket because 'it was way too expensive'." },
        { question: "What did the author ultimately purchase?", options: ["A shirt and blue jeans", "Only a pair of blue jeans", "A jacket and a shirt", "Shoes and a shirt"], correctIndex: 0, explanation: "They decided to buy 'a cheaper casual shirt and a pair of comfortable blue jeans instead'." },
        { question: "What does the author always look for?", options: ["Discounts and sales", "Expensive jackets", "Quiet malls", "Saturday mornings"], correctIndex: 0, explanation: "They say 'I always look carefully for great discounts and seasonal sales'." }
      ]
    },
    level2: {
      textEn: "The global retail industry relies heavily on rapidly changing seasonal trends to drive massive consumer sales. Unfortunately, consumers are constantly encouraged to update their wardrobes frequently, which directly leads to the problematic phenomenon known as fast fashion. Although finding a surprisingly cheap bargain is often thrilling, we must seriously consider the severe environmental impact of producing millions of cheap garments every year. I recently discovered a charming vintage shop in my neighborhood that sells high-quality, pre-owned leather goods and classic clothing. Investing in durable, timeless items rather than disposable fashion is undeniably a much more sustainable and responsible approach to modern shopping.",
      textPt: "O setor de varejo global depende fortemente de tendências sazonais em rápida mudança para impulsionar vendas massivas aos consumidores. Infelizmente, os consumidores são constantemente incentivados a atualizar seus guarda-roupas com frequência, o que leva diretamente ao fenômeno problemático conhecido como moda rápida. Embora encontrar uma pechincha surpreendentemente barata seja frequentemente emocionante, devemos considerar seriamente o grave impacto ambiental de produzir milhões de roupas baratas todos os anos. Descobri recentemente um charmoso brechó no meu bairro que vende artigos de couro usados de alta qualidade e roupas clássicas. Investir em itens duráveis e atemporais, em vez de moda descartável, é inegavelmente uma abordagem muito mais sustentável e responsável para as compras modernas.",
      questions: [
        { question: "What does the retail industry rely heavily on?", options: ["Seasonal trends", "Selling high-quality leather", "Keeping prices high", "Vintage shops"], correctIndex: 0, explanation: "The industry relies heavily on 'rapidly changing seasonal trends'." },
        { question: "What must consumers consider when buying cheap garments?", options: ["The environmental impact", "The thrill of a bargain", "The seasonal trends", "The vintage shops"], correctIndex: 0, explanation: "We must consider 'the severe environmental impact of producing millions of cheap garments'." },
        { question: "What did the author recently discover?", options: ["A vintage shop with high-quality goods", "A fast fashion store", "A cheap garment factory", "A new shopping mall"], correctIndex: 0, explanation: "They discovered 'a charming vintage shop in my neighborhood that sells high-quality, pre-owned leather goods'." },
        { question: "What is presented as a sustainable approach?", options: ["Investing in durable items", "Buying cheap clothes", "Updating wardrobes frequently", "Shopping at the mall"], correctIndex: 0, explanation: "The text concludes 'Investing in durable, timeless items... is undeniably a much more sustainable and responsible approach'." }
      ]
    }
  },
  "profissoes": {
    level1: {
      textEn: "Choosing a career path is a very big and important decision for any young person. Personally, I want to be a teacher when I grow up because I really enjoy helping children learn and discover new things. My older brother works hard as a mechanic at a local garage, where he fixes broken cars and trucks every single day. Next week, my older cousin has a very important job interview to become a registered nurse at the main city hospital. Everyone in this world has completely different talents, interests, and goals for their future.",
      textPt: "Escolher um plano de carreira é uma decisão muito grande e importante para qualquer jovem. Pessoalmente, eu quero ser professor quando crescer porque gosto muito de ajudar as crianças a aprenderem e descobrirem coisas novas. Meu irmão mais velho trabalha duro como mecânico em uma oficina local, onde conserta carros e caminhões quebrados todos os dias. Na próxima semana, meu primo mais velho tem uma entrevista de emprego muito importante para se tornar enfermeiro registrado no hospital principal da cidade. Todos neste mundo têm talentos, interesses e objetivos completamente diferentes para o seu futuro.",
      questions: [
        { question: "Why does the author want to be a teacher?", options: ["Because they enjoy helping children learn", "Because it pays a lot of money", "Because they want to work in a hospital", "Because they like fixing cars"], correctIndex: 0, explanation: "They want to be a teacher 'because I really enjoy helping children learn'." },
        { question: "What is the brother's profession?", options: ["Mechanic", "Teacher", "Nurse", "Driver"], correctIndex: 0, explanation: "The text says 'My older brother works hard as a mechanic'." },
        { question: "What is the cousin preparing for?", options: ["A job interview to be a nurse", "A test to become a teacher", "Buying a new car", "Fixing cars at the hospital"], correctIndex: 0, explanation: "The cousin 'has a very important job interview to become a registered nurse'." },
        { question: "What is the main conclusion of the text?", options: ["Everyone has different talents", "Being a teacher is the best job", "Mechanics make the most money", "It is easy to choose a career"], correctIndex: 0, explanation: "The text concludes: 'Everyone in this world has completely different talents'." }
      ]
    },
    level2: {
      textEn: "The modern corporate workplace is evolving incredibly rapidly due to continuous technological advancements. Today, employers are actively seeking highly skilled candidates who can efficiently manage complex international projects and naturally adapt to mastering new software systems quickly. I recently conducted an interview with a brilliant candidate from overseas, and their unique, diverse perspective proved to be a great, invaluable asset for our entire marketing team. Additionally, working remotely from home has drastically changed how we interact daily; instead of casual office conversations, we rely heavily on scheduling formal virtual meetings. Ultimately, professional flexibility is considered an absolutely key survival skill in this new era.",
      textPt: "O ambiente de trabalho corporativo moderno está evoluindo incrivelmente rápido devido aos contínuos avanços tecnológicos. Hoje, os empregadores buscam ativamente candidatos altamente qualificados que possam gerenciar com eficiência projetos internacionais complexos e se adaptar naturalmente ao domínio de novos sistemas de software rapidamente. Recentemente conduzi uma entrevista com um candidato brilhante do exterior, e sua perspectiva única e diversificada provou ser um grande e inestimável recurso para toda a nossa equipe de marketing. Além disso, trabalhar remotamente de casa mudou drasticamente a forma como interagimos diariamente; em vez de conversas casuais no escritório, dependemos fortemente do agendamento de reuniões virtuais formais. Em última análise, a flexibilidade profissional é considerada uma habilidade de sobrevivência absolutamente essencial nesta nova era.",
      questions: [
        { question: "What skills do employers value in candidates?", options: ["Managing projects and adapting quickly", "Fixing computers", "Working without software", "Traveling overseas"], correctIndex: 0, explanation: "Employers seek candidates who 'can efficiently manage complex international projects and naturally adapt to mastering new software systems'." },
        { question: "Why was the overseas candidate valuable?", options: ["They brought a diverse perspective", "They worked for less money", "They wanted to work remotely", "They avoided virtual meetings"], correctIndex: 0, explanation: "Their 'unique, diverse perspective proved to be a great, invaluable asset'." },
        { question: "How has remote work changed employee interactions?", options: ["Employees hold virtual meetings", "Employees never interact", "Employees travel more", "Employees work longer hours"], correctIndex: 0, explanation: "Instead of casual office conversations, 'we rely heavily on scheduling formal virtual meetings'." },
        { question: "What is considered a key professional skill?", options: ["Flexibility", "Software engineering", "Interviewing", "Working overseas"], correctIndex: 0, explanation: "The text concludes 'professional flexibility is considered an absolutely key survival skill'." }
      ]
    }
  },
  "lugares": {
    level1: {
      textEn: "Even though my town is quite small, it has many interesting and beautiful public places to visit. The lively central square has a spectacular water fountain where many young children like to play in the late afternoon. Right next to the busy square, there is a large, quiet public library filled with thousands of fascinating books. On most Fridays, I usually go to the big movie theater downtown with my best friends to watch the latest releases. The only major problem with my town is that the main bus station is located very far from my house, which means we always have to walk a lot.",
      textPt: "Embora minha cidade seja bem pequena, ela tem muitos lugares públicos interessantes e bonitos para visitar. A animada praça central tem uma espetacular fonte de água onde muitas crianças pequenas gostam de brincar no final da tarde. Bem ao lado da praça movimentada, há uma grande e silenciosa biblioteca pública cheia de milhares de livros fascinantes. Na maioria das sextas-feiras, geralmente vou ao grande cinema do centro com meus melhores amigos para assistir aos últimos lançamentos. O único grande problema com a minha cidade é que a rodoviária principal fica muito longe da minha casa, o que significa que sempre temos que andar muito.",
      questions: [
        { question: "What can be found in the central square?", options: ["A beautiful fountain", "A large bus station", "A movie theater", "Thousands of books"], correctIndex: 0, explanation: "The text mentions 'The lively central square has a spectacular water fountain'." },
        { question: "Where is the large library located?", options: ["Next to the central square", "Far from the house", "Inside the movie theater", "Next to the bus station"], correctIndex: 0, explanation: "The text says 'Right next to the busy square, there is a large, quiet public library'." },
        { question: "When does the author usually visit the movie theater?", options: ["On Fridays", "Every afternoon", "On weekends", "In the morning"], correctIndex: 0, explanation: "They say 'On most Fridays, I usually go to the big movie theater'." },
        { question: "What is the negative aspect of the town?", options: ["The bus station is very far", "The library doesn't have enough books", "The town is too noisy", "The fountain is broken"], correctIndex: 0, explanation: "The only major problem is 'that the main bus station is located very far from my house'." }
      ]
    },
    level2: {
      textEn: "Navigating your way successfully through a massive, busy metropolis requires immense patience and a flawless sense of direction. When I am traveling to new destinations, I actively try not to ignore the intricate architectural details of old historical buildings. Just last month, I eagerly visited an exclusive contemporary art exhibition downtown that was truly captivating and thought-provoking. Unfortunately, to finally get there, I had to walk several exhausting miles around the confusing city center because my domestic flight was severely delayed. While thoroughly exploring public urban places on foot is undeniably tiring, it is also incredibly rewarding and eye-opening.",
      textPt: "Navegar com sucesso por uma metrópole enorme e movimentada exige imensa paciência e um senso de direção impecável. Quando estou viajando para novos destinos, tento ativamente não ignorar os intrincados detalhes arquitetônicos de prédios históricos antigos. Apenas no mês passado, visitei ansiosamente uma exposição de arte contemporânea exclusiva no centro da cidade que foi verdadeiramente cativante e instigante. Infelizmente, para finalmente chegar lá, tive que caminhar várias milhas exaustivas pelo confuso centro da cidade porque meu voo doméstico estava severamente atrasado. Embora explorar minuciosamente os espaços urbanos públicos a pé seja inegavelmente cansativo, é também incrivelmente gratificante e revelador.",
      questions: [
        { question: "What does navigating a busy metropolis require?", options: ["Patience", "A fast car", "Living downtown", "Taking a flight"], correctIndex: 0, explanation: "Navigating a busy metropolis requires 'immense patience and a flawless sense of direction'." },
        { question: "What does the author pay attention to while traveling?", options: ["Architectural details of historical buildings", "The delays of trains", "The cost of flights", "The number of miles they walk"], correctIndex: 0, explanation: "They try not to ignore 'the intricate architectural details of old historical buildings'." },
        { question: "Why did the author walk miles around the city center?", options: ["Because the flight was delayed", "Because they wanted to exercise", "Because they couldn't afford a taxi", "Because the exhibition was closed"], correctIndex: 0, explanation: "They walked miles 'because my domestic flight was severely delayed'." },
        { question: "How does the author describe exploring on foot?", options: ["Tiring, but rewarding", "A waste of time", "Very fast", "Boring and difficult"], correctIndex: 0, explanation: "They state it is 'ineniably tiring, it is also incredibly rewarding'." }
      ]
    }
  },
  "animais": {
    level1: {
      textEn: "Animals are truly fascinating and wonderful creatures that share our planet. My absolute favorite animal in the world is the dog because it is known to be very friendly, loyal, and protective of its family. My closest neighbor actually has a big, fluffy dog that loves to bark loudly whenever the postman arrives. Conversely, some people much prefer having cats as pets because they are generally very quiet, independent, and extremely clean. Last summer during our vacation, we went to the city zoo and saw magnificent lions, giant gray elephants, and funny little monkeys playfully jumping high up in the trees.",
      textPt: "Os animais são criaturas verdadeiramente fascinantes e maravilhosas que compartilham nosso planeta. O meu animal favorito absoluto no mundo é o cachorro, porque é conhecido por ser muito amigável, leal e protetor de sua família. Meu vizinho mais próximo, na verdade, tem um cachorro grande e fofo que adora latir alto sempre que o carteiro chega. Por outro lado, algumas pessoas preferem muito mais ter gatos como animais de estimação porque geralmente são muito quietos, independentes e extremamente limpos. No verão passado, durante nossas férias, fomos ao zoológico da cidade e vimos leões magníficos, elefantes cinzentos gigantes e macaquinhos engraçados pulando de forma divertida no alto das árvores.",
      questions: [
        { question: "Why does the author favor dogs?", options: ["Because they are friendly", "Because they are quiet", "Because they jump in trees", "Because they bark a lot"], correctIndex: 0, explanation: "The author favors dogs 'because it is known to be very friendly, loyal, and protective'." },
        { question: "What does the neighbor's dog like to do?", options: ["Bark", "Sleep all day", "Jump in trees", "Chase cats"], correctIndex: 0, explanation: "The neighbor has a big dog that 'loves to bark loudly'." },
        { question: "Why do some people prefer cats?", options: ["Because they are quiet", "Because they are friendly", "Because they are big", "Because they like to bark"], correctIndex: 0, explanation: "People prefer cats 'because they are generally very quiet'." },
        { question: "Where did they see lions and elephants?", options: ["At the zoo", "In the neighbor's yard", "At the park", "In the forest"], correctIndex: 0, explanation: "They 'went to the city zoo and saw magnificent lions, giant gray elephants'." }
      ]
    },
    level2: {
      textEn: "Global wildlife conservation is absolutely essential for maintaining the delicate balance of our planet's rich biodiversity. Unfortunately, ever since the dawn of the industrial revolution, the grim timeline of global species extinction has accelerated quite alarmingly across all continents. Just last month, I had the privilege of visiting a massive coastal aquarium that focuses extensively on rescuing and rehabilitating injured marine animals. The educational guides there strongly emphasized that continuously educating the general public about these majestic, vulnerable creatures is truly the critical first step toward ultimately saving them from permanent extinction.",
      textPt: "A conservação da vida selvagem global é absolutamente essencial para manter o delicado equilíbrio da rica biodiversidade do nosso planeta. Infelizmente, desde o alvorecer da revolução industrial, a sombria linha do tempo da extinção de espécies globais acelerou de forma bastante alarmante em todos os continentes. Apenas no mês passado, tive o privilégio de visitar um enorme aquário costeiro que se concentra extensivamente em resgatar e reabilitar animais marinhos feridos. Os guias educacionais lá enfatizaram fortemente que educar continuamente o público em geral sobre essas criaturas majestosas e vulneráveis é verdadeiramente o primeiro passo crítico para, em última análise, salvá-las da extinção permanente.",
      questions: [
        { question: "What is the primary reason for wildlife conservation?", options: ["To maintain biodiversity", "To build more aquariums", "To prevent hunting", "To accelerate extinction"], correctIndex: 0, explanation: "It is 'absolutely essential for maintaining the delicate balance of our planet's rich biodiversity'." },
        { question: "What has happened since the industrial revolution?", options: ["Species extinction has accelerated alarmingly", "Extinction has stopped", "Biodiversity has increased", "Marine animals were rescued"], correctIndex: 0, explanation: "Since then, 'the grim timeline of global species extinction has accelerated quite alarmingly'." },
        { question: "What was the focus of the aquarium?", options: ["Rescuing marine animals", "Training sharks to hunt", "Breeding lions", "Selling exotic fish"], correctIndex: 0, explanation: "The aquarium 'focuses extensively on rescuing and rehabilitating injured marine animals'." },
        { question: "What is the first step toward saving these creatures?", options: ["Educating the public", "Stopping the industrial revolution", "Closing aquariums", "Feeding them more"], correctIndex: 0, explanation: "'Educating the general public about these majestic, vulnerable creatures is truly the critical first step'." }
      ]
    }
  },
  "culinaria": {
    level1: {
      textEn: "Knowing how to cook your own meals is a very useful and practical daily skill for everyone. On most mornings, I usually choose to quickly boil a couple of eggs and gently fry some crispy bacon for a hearty breakfast. Later in the day, if you want to make a healthy green salad, you have to carefully chop fresh vegetables like tomatoes and cucumbers with a very sharp kitchen knife. Meanwhile, my talented mother always likes to lovingly bake delicious, sweet chocolate cakes in the hot oven. I have learned that strictly following a written recipe really helps you measure and mix all the ingredients perfectly.",
      textPt: "Saber cozinhar as próprias refeições é uma habilidade diária muito útil e prática para todos. Na maioria das manhãs, eu geralmente escolho ferver rapidamente alguns ovos e fritar suavemente um bacon crocante para um café da manhã reforçado. Mais tarde no dia, se você quiser fazer uma salada verde saudável, você tem que picar cuidadosamente vegetais frescos como tomates e pepinos com uma faca de cozinha muito afiada. Enquanto isso, minha talentosa mãe sempre gosta de assar com amor bolos de chocolate deliciosos e doces no forno quente. Aprendi que seguir estritamente uma receita escrita realmente ajuda você a medir e misturar perfeitamente todos os ingredientes.",
      questions: [
        { question: "What does the author usually make for breakfast?", options: ["Boiled eggs and bacon", "Chocolate cakes", "A fresh salad", "Cereal and milk"], correctIndex: 0, explanation: "They usually 'choose to quickly boil a couple of eggs and gently fry some crispy bacon'." },
        { question: "What tool is used to chop vegetables?", options: ["A sharp knife", "A spoon", "An oven", "A fork"], correctIndex: 0, explanation: "You chop fresh vegetables 'with a very sharp kitchen knife'." },
        { question: "What does the mother like to bake?", options: ["Chocolate cakes", "Bread", "Cookies", "Pizza"], correctIndex: 0, explanation: "The mother 'likes to lovingly bake delicious, sweet chocolate cakes'." },
        { question: "Why is following a recipe helpful?", options: ["It helps mix ingredients perfectly", "It makes cooking faster", "It cleans the kitchen", "It is required by law"], correctIndex: 0, explanation: "Following a written recipe 'really helps you measure and mix all the ingredients perfectly'." }
      ]
    },
    level2: {
      textEn: "Genuinely mastering the advanced culinary arts requires not only raw talent but also immense patience and endless flavor experimentation. A truly great, world-class chef always knows exactly how to perfectly balance conflicting sweet, salty, and spicy flavor profiles within a single, cohesive dish. Yesterday evening, I bravely attempted a highly complex gourmet recipe that involved skillfully pouring a rich, delicate wine sauce over perfectly grilled organic chicken. Constantly tasting the food while you are actively cooking is incredibly important, as it ensures that the subtle seasoning is just right before serving. Finally, creatively presenting the food beautifully on a warm plate is also considered a crucial aspect of fine dining.",
      textPt: "Dominar genuinamente as artes culinárias avançadas exige não apenas talento bruto, mas também imensa paciência e experimentação de sabores sem fim. Um chef verdadeiramente grande e de classe mundial sempre sabe exatamente como equilibrar perfeitamente perfis conflitantes de sabores doces, salgados e picantes dentro de um único prato coeso. Ontem à noite, tentei corajosamente uma receita gourmet altamente complexa que envolvia derramar habilmente um molho de vinho rico e delicado sobre frango orgânico perfeitamente grelhado. Provar constantemente a comida enquanto você está cozinhando ativamente é incrivelmente importante, pois garante que o tempero sutil esteja no ponto antes de servir. Por fim, apresentar criativamente a comida de forma bela em um prato aquecido também é considerado um aspecto crucial da alta gastronomia.",
      questions: [
        { question: "What does mastering the culinary arts require?", options: ["Patience and experimentation", "A sharp knife and an oven", "Only expensive ingredients", "Cooking very fast"], correctIndex: 0, explanation: "It requires 'immense patience and endless flavor experimentation'." },
        { question: "What should a great chef know how to balance?", options: ["Sweet, salty, and spicy flavors", "Water and oil", "Meat and vegetables", "Time and money"], correctIndex: 0, explanation: "A great chef knows how to balance 'sweet, salty, and spicy flavor profiles'." },
        { question: "Why is tasting the food while cooking important?", options: ["It ensures the seasoning is just right", "It makes you less hungry", "It cools down the food", "It is a rule in the recipe"], correctIndex: 0, explanation: "Tasting the food 'ensures that the subtle seasoning is just right before serving'." },
        { question: "What is also considered crucial in cooking?", options: ["Presenting the food beautifully on a plate", "Washing the dishes immediately", "Buying a new oven", "Using a lot of salt"], correctIndex: 0, explanation: "'Creatively presenting the food beautifully on a warm plate is also considered a crucial aspect'." }
      ]
    }
  },
  "tecnologia": {
    level1: {
      textEn: "In my daily life, I heavily rely on my personal smartphone and lightweight laptop to accomplish almost every task. In order to safely access the internet and read my emails, I always make sure to type a secret, complicated password. During my free time, I often enjoy downloading new entertainment apps and exciting puzzle games from the digital store. Whenever the screen indicates that the battery is running low, I quickly grab a compatible charger and plug it into the wall socket. Modern devices are designed to be user-friendly; for instance, it is very easy to type quickly on the digital keyboard and comfortably look at the bright, high-resolution screen.",
      textPt: "Na minha vida diária, dependo muito do meu smartphone pessoal e do meu laptop leve para realizar quase todas as tarefas. Para acessar a internet com segurança e ler meus e-mails, sempre me certifico de digitar uma senha secreta e complicada. Durante meu tempo livre, costumo gostar de baixar novos aplicativos de entretenimento e emocionantes jogos de quebra-cabeça da loja digital. Sempre que a tela indica que a bateria está acabando, pego rapidamente um carregador compatível e o conecto na tomada da parede. Dispositivos modernos são projetados para serem fáceis de usar; por exemplo, é muito fácil digitar rapidamente no teclado digital e olhar confortavelmente para a tela brilhante e de alta resolução.",
      questions: [
        { question: "What devices does the author use every day?", options: ["Smartphone and laptop", "Television and radio", "Tablet and smartwatch", "Camera and printer"], correctIndex: 0, explanation: "The text states 'I heavily rely on my personal smartphone and lightweight laptop'." },
        { question: "What is needed to use the internet?", options: ["A secret password", "A new app", "A charger", "A printer"], correctIndex: 0, explanation: "They say 'In order to safely access the internet... I always make sure to type a secret, complicated password'." },
        { question: "What does the author often download?", options: ["New apps and games", "Movies and music", "Books and photos", "Viruses"], correctIndex: 0, explanation: "They often enjoy 'downloading new entertainment apps and exciting puzzle games'." },
        { question: "What do you use when the battery is low?", options: ["A charger", "A keyboard", "A screen", "A password"], correctIndex: 0, explanation: "They state 'Whenever the screen indicates that the battery is running low, I quickly grab a compatible charger'." }
      ]
    },
    level2: {
      textEn: "The widespread adoption of cloud computing technology has fundamentally and irreversibly revolutionized how modern businesses and individuals securely store their digital data. Instead of precariously keeping all your vulnerable files on a single, fragile local hard drive, you can seamlessly upload everything to a highly secure, encrypted remote server. This amazing capability makes it incredibly easy to logically organize thousands of files into neat digital folders and instantly access them from absolutely any internet-connected device in the world. However, despite these benefits, you must always remain highly vigilant and extremely careful with disguised malicious links that could potentially steal your sensitive private data. Therefore, regularly backing up your important files and consistently updating your operating software is considered absolutely essential for cybersecurity.",
      textPt: "A ampla adoção da tecnologia de computação em nuvem revolucionou de forma fundamental e irreversível a maneira como empresas modernas e indivíduos armazenam com segurança seus dados digitais. Em vez de manter precariamente todos os seus arquivos vulneráveis em um único e frágil disco rígido local, você pode fazer upload perfeitamente de tudo para um servidor remoto altamente seguro e criptografado. Essa capacidade incrível torna incrivelmente fácil organizar logicamente milhares de arquivos em pastas digitais limpas e acessá-los instantaneamente de absolutamente qualquer dispositivo conectado à internet no mundo. No entanto, apesar desses benefícios, você deve sempre permanecer altamente vigilante e extremamente cuidadoso com links maliciosos disfarçados que podem potencialmente roubar seus dados privados sensíveis. Portanto, fazer backup regularmente de seus arquivos importantes e atualizar consistentemente seu software operacional é considerado absolutamente essencial para a segurança cibernética.",
      questions: [
        { question: "How has cloud computing changed data storage?", options: ["You can upload files to a secure server", "You must keep files on a local hard drive", "It deleted all digital folders", "It made passwords unnecessary"], correctIndex: 0, explanation: "You can 'seamlessly upload everything to a highly secure, encrypted remote server'." },
        { question: "What is an advantage of using digital folders in the cloud?", options: ["Accessing files from any device", "Avoiding software updates", "Increasing battery life", "Listening to music offline"], correctIndex: 0, explanation: "It makes it easy to 'instantly access them from absolutely any internet-connected device'." },
        { question: "What danger should users be careful about?", options: ["Malicious links that could steal data", "Uploading too many photos", "Forgetting the charger", "Organizing files too often"], correctIndex: 0, explanation: "You must be careful with 'disguised malicious links that could potentially steal your sensitive private data'." },
        { question: "What is considered essential for data security?", options: ["Regularly backing up and updating software", "Sharing passwords", "Using a local hard drive", "Clicking on all links"], correctIndex: 0, explanation: "'Regularly backing up your important files and consistently updating your operating software is considered absolutely essential'." }
      ]
    }
  },
  "redes-sociais": {
    level1: {
      textEn: "Using social media applications on my phone is definitely a fun and fast way to stay closely connected with all my friends and family members. I really enjoy taking the time to post beautiful, bright photos from my weekend trips and happily share them on my public profile page for everyone to see. When I casually scroll through my daily feed during my lunch break, I can easily leave a nice, supportive comment or simply tap to like the latest pictures uploaded by my closest friends. Additionally, I learned that using a popular hashtag in your posts significantly helps other people around the world find and join conversations about interesting, trending topics.",
      textPt: "Usar aplicativos de mídia social no meu telefone é definitivamente uma maneira rápida e divertida de ficar conectado de perto com todos os meus amigos e familiares. Eu realmente gosto de reservar um tempo para postar fotos lindas e brilhantes das minhas viagens de fim de semana e compartilhá-las alegremente na minha página de perfil público para que todos vejam. Quando rolo casualmente o meu feed diário durante o meu horário de almoço, posso facilmente deixar um comentário agradável e encorajador ou simplesmente tocar para curtir as fotos mais recentes enviadas por meus amigos mais próximos. Além disso, aprendi que usar uma hashtag popular em suas postagens ajuda significativamente outras pessoas ao redor do mundo a encontrar e participar de conversas sobre tópicos interessantes e em alta.",
      questions: [
        { question: "What is social media used for in the text?", options: ["To connect with friends", "To download games", "To buy new clothes", "To watch movies"], correctIndex: 0, explanation: "It is a 'fun and fast way to stay closely connected with all my friends'." },
        { question: "Where does the author share photos?", options: ["On their profile", "In a private message", "In an email", "On a website"], correctIndex: 0, explanation: "They 'happily share them on my public profile page'." },
        { question: "What can the author do while scrolling the feed?", options: ["Leave a comment or like pictures", "Delete old photos", "Change their password", "Call their friends"], correctIndex: 0, explanation: "They can 'leave a nice, supportive comment or simply tap to like the latest pictures'." },
        { question: "What is the purpose of a hashtag?", options: ["To help people find interesting topics", "To protect your password", "To charge your phone", "To block a follower"], correctIndex: 0, explanation: "A popular hashtag 'significantly helps other people around the world find and join conversations about interesting, trending topics'." }
      ]
    },
    level2: {
      textEn: "In today's highly competitive corporate landscape, modern digital marketing strategies rely exceptionally heavily on complex, constantly changing social media algorithms to reach consumers. Popular internet influencers continuously attempt to strategically create viral, eye-catching videos hoping to spontaneously gain hundreds of thousands of new, loyal followers overnight. Furthermore, the psychological tactic of posting an engaging, exclusive video story that permanently disappears in exactly 24 hours effectively creates a powerful sense of urgency among the audience. Given how much data these platforms collect daily, it is incredibly important that users take the necessary time to adjust their account privacy settings to ensure their sensitive personal data is fiercely protected from aggressive, unwanted corporate access.",
      textPt: "No cenário corporativo altamente competitivo de hoje, as estratégias modernas de marketing digital dependem excepcionalmente forte de algoritmos complexos e em constante mudança das mídias sociais para alcançar os consumidores. Influenciadores populares da internet tentam continuamente criar vídeos virais e atraentes estrategicamente na esperança de ganhar espontaneamente centenas de milhares de novos seguidores leais da noite para o dia. Além disso, a tática psicológica de postar uma história de vídeo envolvente e exclusiva que desaparece permanentemente em exatamente 24 horas cria efetivamente um poderoso senso de urgência entre o público. Considerando a quantidade de dados que essas plataformas coletam diariamente, é incrivelmente importante que os usuários reservem o tempo necessário para ajustar as configurações de privacidade da conta para garantir que seus dados pessoais confidenciais sejam ferozmente protegidos contra acesso corporativo agressivo e indesejado.",
      questions: [
        { question: "What does digital marketing rely on?", options: ["Social media algorithms", "Private messages", "Hashtags only", "Local hard drives"], correctIndex: 0, explanation: "It relies 'exceptionally heavily on complex, constantly changing social media algorithms'." },
        { question: "What is the goal of creating a viral video?", options: ["To gain thousands of new followers", "To delete the profile", "To hide personal data", "To adjust privacy settings"], correctIndex: 0, explanation: "They hope 'to spontaneously gain hundreds of thousands of new, loyal followers overnight'." },
        { question: "What creates a sense of urgency on social platforms?", options: ["Posting a story that disappears in 24 hours", "Uploading a photo to the feed", "Leaving a short comment", "Following many people"], correctIndex: 0, explanation: "Posting an 'engaging, exclusive video story that permanently disappears in exactly 24 hours effectively creates a powerful sense of urgency'." },
        { question: "Why should you adjust your privacy settings?", options: ["To protect personal data from unwanted access", "To get more followers", "To make a video go viral", "To see more ads"], correctIndex: 0, explanation: "To ensure 'their sensitive personal data is fiercely protected from aggressive, unwanted corporate access'." }
      ]
    }
  }
};

function injectData(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');

  for (const [id, reading] of Object.entries(data)) {
    const scenarioStart = content.indexOf(`id: "${id}"`);
    if (scenarioStart === -1) continue;

    let nextId = content.indexOf('id: "', scenarioStart + 10);
    if (nextId === -1) nextId = content.length;
    let section = content.slice(scenarioStart, nextId);

    const readingStr = 'reading: ' + JSON.stringify(reading, null, 6);
    const readingStart = section.indexOf('    reading: {');
    const vocabStart = section.indexOf('    vocabulary: [');
    
    if (readingStart !== -1 && vocabStart !== -1 && vocabStart > readingStart) {
      section = section.slice(0, readingStart) + '    ' + readingStr + ',\n' + section.slice(vocabStart);
    }

    content = content.slice(0, scenarioStart) + section + content.slice(nextId);
  }

  fs.writeFileSync(filePath, content);
}

injectData('./data/scenarios2.ts');
console.log("Injected MEDIUM Extended Reading into scenarios2.ts");
