const fs = require('fs');

const data = {
  "familia": {
    level1: {
      textEn: "My family is relatively small, but we are extremely close and support each other through everything. I live in a beautiful, cozy house in a quiet neighborhood with my mother and my younger brother. My mother is a very dedicated and hardworking teacher. She teaches history at a local high school, and she is always incredibly kind, patient, and understanding with all of her students. Every evening, she spends hours preparing her lessons for the next day. My brother is ten years old, and he has boundless energy. He absolutely loves playing soccer with his friends in the neighborhood park every afternoon until the sun goes down. We have a very special family tradition that we never, ever miss, no matter how busy our schedules get during the week. Every Sunday afternoon, we travel by train to visit our dear grandmother who lives in a peaceful house in the countryside. As soon as we arrive, the house smells wonderful because she always bakes the best chocolate cake for us. We spend the entire day sitting on the porch, talking, laughing, and sharing stories about our week.",
      textPt: "Minha família é relativamente pequena, mas somos extremamente próximos e nos apoiamos em tudo. Eu moro em uma casa bonita e aconchegante em um bairro tranquilo com minha mãe e meu irmão mais novo. Minha mãe é uma professora muito dedicada e trabalhadora. Ela ensina história em uma escola secundária local e é sempre incrivelmente gentil, paciente e compreensiva com todos os seus alunos. Todas as noites, ela passa horas preparando suas aulas para o dia seguinte. Meu irmão tem dez anos e tem uma energia inesgotável. Ele absolutamente adora jogar futebol com seus amigos no parque do bairro todas as tardes até o sol se pôr. Nós temos uma tradição de família muito especial que nunca, jamais perdemos, por mais ocupadas que nossas agendas fiquem durante a semana. Todo domingo à tarde, viajamos de trem para visitar nossa querida avó que mora em uma casa pacífica no interior. Assim que chegamos, a casa tem um cheiro maravilhoso porque ela sempre assa o melhor bolo de chocolate para nós. Passamos o dia inteiro sentados na varanda, conversando, rindo e compartilhando histórias sobre nossa semana.",
      questions: [
        { question: "Who does the author live with?", options: ["Mother and brother", "Father and sister", "Grandmother only", "Cousins"], correctIndex: 0, explanation: "The text says 'I live in a beautiful, cozy house... with my mother and my younger brother'." },
        { question: "What is the mother's profession?", options: ["Teacher", "Doctor", "Engineer", "Nurse"], correctIndex: 0, explanation: "The text says 'My mother is a very dedicated and hardworking teacher'." },
        { question: "What does the brother love to do?", options: ["Play soccer", "Eat cake", "Visit grandmother", "Read books"], correctIndex: 0, explanation: "The brother 'absolutely loves playing soccer with his friends'." },
        { question: "When do they visit their grandmother?", options: ["Every Sunday", "Every Saturday", "Once a month", "On holidays"], correctIndex: 0, explanation: "They visit 'Every Sunday afternoon'." }
      ]
    },
    level2: {
      textEn: "Family gatherings are considered a profoundly important tradition in our culture, acting as a vital bridge between different generations and preserving our heritage. Every major holiday, my entire extended family comes together at my uncle's expansive house situated near a beautiful, serene lake. The complex preparation for these events usually starts several days in advance, with every family member enthusiastically contributing their unique signature dishes to create a massive feast. I have a remarkably large number of cousins, and whenever we meet, we always spend hours sharing hilarious stories about our childhood adventures and updating each other on our recent professional and personal achievements. Last year's gathering was particularly memorable and emotional because my older sister finally got married in a breathtakingly beautiful outdoor ceremony right by the water. Because of that joyous event, I now have a wonderful brother-in-law who has rapidly become a great, dependable friend to all of us. It is truly amazing to observe how fast our family is continuously growing with new additions. Ultimately, these lively gatherings serve as a beautiful reminder of the strong, unbreakable bonds we share, completely regardless of the long distances that separate our daily lives.",
      textPt: "As reuniões familiares são consideradas uma tradição profundamente importante em nossa cultura, atuando como uma ponte vital entre as diferentes gerações e preservando nossa herança. Em todo grande feriado, toda a minha família estendida se reúne na espaçosa casa do meu tio, situada perto de um belo e sereno lago. A complexa preparação para esses eventos geralmente começa com vários dias de antecedência, com cada membro da família contribuindo com entusiasmo com seus pratos exclusivos para criar um banquete enorme. Tenho um número notavelmente grande de primos e, sempre que nos encontramos, passamos horas compartilhando histórias hilárias sobre nossas aventuras de infância e nos atualizando sobre nossas recentes conquistas profissionais e pessoais. O encontro do ano passado foi particularmente memorável e emocionante porque minha irmã mais velha finalmente se casou em uma cerimônia ao ar livre de tirar o fôlego, bem na beira da água. Por causa desse evento alegre, agora tenho um cunhado maravilhoso que rapidamente se tornou um grande e confiável amigo para todos nós. É realmente incrível observar o quão rápido nossa família cresce continuamente com novas adições. Em última análise, essas animadas reuniões servem como um belo lembrete dos fortes e inquebráveis laços que compartilhamos, totalmente independentes das longas distâncias que separam nossas vidas diárias.",
      questions: [
        { question: "Where do the family gatherings happen?", options: ["At the uncle's house", "At the grandmother's house", "At the author's house", "In a restaurant"], correctIndex: 0, explanation: "They come together 'at my uncle's expansive house situated near a beautiful, serene lake'." },
        { question: "What do the cousins usually do together?", options: ["Share funny stories", "Play soccer", "Cook dinner", "Watch movies"], correctIndex: 0, explanation: "They 'spend hours sharing hilarious stories about our childhood adventures'." },
        { question: "What happened to the older sister last year?", options: ["She got married", "She moved to another city", "She had a baby", "She bought a house"], correctIndex: 0, explanation: "The text says 'my older sister finally got married in a breathtakingly beautiful outdoor ceremony'." },
        { question: "How does the author describe the family's growth?", options: ["Amazing and fast", "Slow and steady", "Difficult to manage", "Unexpected"], correctIndex: 0, explanation: "They say 'It is truly amazing to observe how fast our family is continuously growing'." }
      ]
    }
  },
  "amigos": {
    level1: {
      textEn: "I am extremely lucky because I have a truly great group of friends, and they are incredibly important in my everyday life. We do almost everything together. My absolute best friend in the whole world is a girl named Anna. She is always incredibly happy, energetic, and completely ready to help anyone who has a problem. We really like to meet up at the enormous public park in the center of our bustling city every single weekend. Sometimes, if the weather is exceptionally sunny and warm, we invite several other friends from our neighborhood and organize a massive picnic under the shade of the tall oak trees. Everyone brings something different, so we always have a huge variety of snacks and drinks to share. We sit on the grass and talk for hours about our favorite movies and music. We eat delicious homemade sandwiches, share funny jokes, and have a tremendous amount of fun together playing simple outdoor games. I firmly believe that having good, reliable friends definitely makes life much better, happier, and significantly more exciting.",
      textPt: "Tenho muita sorte porque tenho um grupo de amigos realmente ótimo, e eles são incrivelmente importantes no meu dia a dia. Nós fazemos quase tudo juntos. Minha melhor amiga no mundo inteiro é uma garota chamada Anna. Ela é sempre incrivelmente feliz, enérgica e totalmente pronta para ajudar qualquer pessoa que tenha um problema. Nós gostamos muito de nos encontrar no enorme parque público no centro da nossa movimentada cidade todo santo fim de semana. Às vezes, se o tempo estiver excepcionalmente ensolarado e quente, convidamos vários outros amigos do nosso bairro e organizamos um enorme piquenique à sombra dos altos carvalhos. Todos trazem algo diferente, então sempre temos uma grande variedade de lanches e bebidas para compartilhar. Sentamos na grama e conversamos por horas sobre nossos filmes e músicas favoritos. Comemos deliciosos sanduíches caseiros, compartilhamos piadas engraçadas e nos divertimos tremendamente juntos jogando jogos simples ao ar livre. Acredito firmemente que ter bons e confiáveis amigos definitivamente torna a vida muito melhor, mais feliz e significativamente mais emocionante.",
      questions: [
        { question: "Who is the author's best friend?", options: ["Anna", "Maria", "John", "Sarah"], correctIndex: 0, explanation: "The text says 'My absolute best friend in the whole world is a girl named Anna'." },
        { question: "Where do they usually meet up?", options: ["At the park", "At the mall", "At school", "At a cafe"], correctIndex: 0, explanation: "They 'meet up at the enormous public park'." },
        { question: "What do they eat during the picnic?", options: ["Sandwiches", "Pizza", "Cake", "Fruit"], correctIndex: 0, explanation: "They 'eat delicious homemade sandwiches'." },
        { question: "What is the final message of the text?", options: ["Good friends make life better", "Picnics are fun", "Weekends are for sleeping", "You should invite everyone"], correctIndex: 0, explanation: "The text ends by saying 'having good, reliable friends definitely makes life much better'." }
      ]
    },
    level2: {
      textEn: "Building and maintaining a lasting friendship is an intricate, deeply rewarding process that unequivocally requires mutual trust, seemingly endless patience, and unwavering honesty over the course of many years. It is perfectly normal and even healthy for individuals to have occasional disagreements or conflicting opinions from time to time. Whenever I find myself arguing with my friends over a misunderstanding, I consciously try to take a step back, sincerely apologize if I am in the wrong, and genuinely strive to understand their unique point of view before the situation has a chance to escalate unnecessarily. Furthermore, it is absolutely essential to fiercely protect your friends' deepest secrets and to proactively step in to offer assistance when someone is going through an emotionally difficult time. While mere acquaintances might only be present for the joyful celebrations and easy moments, a true, lifelong friend will consistently stand by your side and support you through your absolute worst moments, darkest days, and greatest personal challenges. This steadfast loyalty is the defining characteristic of true friendship.",
      textPt: "Construir e manter uma amizade duradoura é um processo intrincado e profundamente gratificante que requer inequivocamente confiança mútua, paciência aparentemente infinita e honestidade inabalável ao longo de muitos anos. É perfeitamente normal e até saudável que os indivíduos tenham desentendimentos ocasionais ou opiniões conflitantes de tempos em tempos. Sempre que me vejo discutindo com meus amigos por causa de um mal-entendido, tento conscientemente dar um passo para trás, pedir desculpas sinceramente se estiver errado e me esforçar genuinamente para entender o ponto de vista único deles antes que a situação tenha a chance de escalar desnecessariamente. Além disso, é absolutamente essencial proteger ferozmente os segredos mais profundos de seus amigos e intervir proativamente para oferecer assistência quando alguém está passando por um momento emocionalmente difícil. Embora meros conhecidos possam estar presentes apenas para as celebrações alegres e momentos fáceis, um amigo verdadeiro e para toda a vida permanecerá consistentemente ao seu lado e o apoiará nos seus piores momentos absolutos, dias mais sombrios e maiores desafios pessoais. Essa lealdade inabalável é a característica definidora da verdadeira amizade.",
      questions: [
        { question: "What does friendship require, according to the text?", options: ["Trust and honesty", "Money and time", "Similar hobbies", "Living close to each other"], correctIndex: 0, explanation: "The text states it requires 'mutual trust, seemingly endless patience, and unwavering honesty'." },
        { question: "What does the author do after an argument?", options: ["Apologizes and tries to understand", "Ignores the friend", "Waits for the friend to apologize", "Stops talking to them"], correctIndex: 0, explanation: "They 'sincerely apologize if I am in the wrong, and genuinely strive to understand their unique point of view'." },
        { question: "What is considered essential in a friendship?", options: ["Keeping secrets and helping out", "Going to parties together", "Agreeing on everything", "Buying expensive gifts"], correctIndex: 0, explanation: "It is 'absolutely essential to fiercely protect your friends' deepest secrets and to proactively step in to offer assistance'." },
        { question: "When will a true friend support you?", options: ["Through your worst moments", "Only when you are happy", "Only when you have money", "Only at school"], correctIndex: 0, explanation: "A true friend will 'consistently stand by your side and support you through your absolute worst moments'." }
      ]
    }
  },
  "corpo": {
    level1: {
      textEn: "I use my amazing body every single day from the moment I wake up until I go to sleep to do a wide variety of wonderful and exciting things. My body completely allows me to safely explore the fascinating world all around me. I use my bright eyes to clearly see beautiful, vivid colors in the morning sky and to read the pages of my absolute favorite adventure books. I use my strong, fast legs to walk down the street to my school and to run freely in the large park with my enthusiastic friends. My hands are extremely useful and constantly busy because they help me securely hold my heavy school books, smoothly draw imaginative pictures on blank paper, and carefully write my full name. Because our complex bodies tirelessly do so much for us without stopping, it is highly important to take exceptionally good care of them. You must meticulously wash your hands with soap before eating any meal and remember to brush your teeth thoroughly at least twice a day to ensure your body remains remarkably healthy, strong, and clean.",
      textPt: "Eu uso meu corpo incrível todos os dias, desde o momento em que acordo até ir dormir, para fazer uma grande variedade de coisas maravilhosas e emocionantes. Meu corpo me permite explorar com segurança o mundo fascinante ao meu redor. Uso meus olhos brilhantes para ver claramente cores bonitas e vivas no céu da manhã e para ler as páginas dos meus livros de aventura favoritos. Uso minhas pernas fortes e rápidas para caminhar pela rua até a minha escola e para correr livremente no grande parque com meus amigos entusiasmados. Minhas mãos são extremamente úteis e constantemente ocupadas porque me ajudam a segurar firmemente meus pesados livros escolares, desenhar quadros imaginativos suavemente em papel em branco e escrever cuidadosamente meu nome completo. Como nossos corpos complexos fazem incansavelmente tanto por nós sem parar, é altamente importante cuidar excepcionalmente bem deles. Você deve lavar meticulosamente as mãos com sabão antes de comer qualquer refeição e lembrar-se de escovar os dentes completamente pelo menos duas vezes ao dia para garantir que seu corpo permaneça notavelmente saudável, forte e limpo.",
      questions: [
        { question: "What does the author use to see colors?", options: ["Eyes", "Ears", "Nose", "Mouth"], correctIndex: 0, explanation: "The text says 'I use my bright eyes to clearly see beautiful, vivid colors'." },
        { question: "How does the author go to school?", options: ["By walking", "By bus", "By car", "By bicycle"], correctIndex: 0, explanation: "They say 'I use my strong, fast legs to walk down the street to my school'." },
        { question: "What do the hands help the author do?", options: ["Hold books and write", "Eat and drink", "Play sports", "Clean the house"], correctIndex: 0, explanation: "Hands help them 'hold my heavy school books, smoothly draw imaginative pictures... and carefully write my full name'." },
        { question: "What should you do to keep your body healthy?", options: ["Wash hands and brush teeth", "Sleep all day", "Eat candy", "Never go outside"], correctIndex: 0, explanation: "You must 'wash your hands with soap before eating any meal and remember to brush your teeth'." }
      ]
    },
    level2: {
      textEn: "Consistently taking comprehensive care of your physical health is absolutely vital for ensuring a long, genuinely happy, and highly active life free of debilitating ailments. Unfortunately, in today's increasingly sedentary modern society, many young professionals frequently experience chronic, agonizing back or shoulder pain simply because they sit rigidly staring at a bright computer screen at a desk all day long without engaging in any meaningful physical movement. To effectively prevent this severe type of muscular discomfort, you should make it a non-negotiable daily habit to thoroughly stretch your stiff muscles regularly and take short, brisk walking breaks every single hour. Furthermore, if you accidentally hurt your knee or twist your ankle while aggressively exercising at the gym, you must never foolishly ignore the sharp pain. You should immediately rest the affected area, apply a cold ice pack to rapidly reduce the swelling, and perhaps elevate the injured limb. Ultimately, paying close attention and patiently listening to your body's subtle warning signals is undisputedly the absolute best way to avoid sustaining serious, long-term physical injuries.",
      textPt: "Cuidar de forma consistente e abrangente de sua saúde física é absolutamente vital para garantir uma vida longa, genuinamente feliz e altamente ativa, livre de doenças debilitantes. Infelizmente, na sociedade moderna cada vez mais sedentária de hoje, muitos jovens profissionais frequentemente experimentam dores crônicas e agonizantes nas costas ou nos ombros simplesmente porque ficam sentados rigidamente olhando para a tela brilhante de um computador em uma mesa o dia todo sem se envolver em nenhum movimento físico significativo. Para prevenir eficazmente esse tipo severo de desconforto muscular, você deve fazer disso um hábito diário inegociável alongar completamente seus músculos rígidos regularmente e fazer pausas curtas e rápidas para caminhar a cada hora. Além disso, se você acidentalmente machucar o joelho ou torcer o tornozelo enquanto se exercita agressivamente na academia, você nunca deve ignorar tolamente a dor aguda. Você deve descansar imediatamente a área afetada, aplicar uma bolsa de gelo frio para reduzir rapidamente o inchaço e, talvez, elevar o membro machucado. Em última análise, prestar muita atenção e ouvir pacientemente os sutis sinais de alerta do seu corpo é indiscutivelmente a melhor maneira absoluta de evitar sofrer lesões físicas graves e de longo prazo.",
      questions: [
        { question: "Why do many people experience back or shoulder pain?", options: ["Because they sit at a desk all day", "Because they exercise too much", "Because they sleep poorly", "Because they lift heavy things"], correctIndex: 0, explanation: "They have pain 'because they sit rigidly staring at a bright computer screen at a desk all day long'." },
        { question: "How can you prevent muscle pain at work?", options: ["Stretch your muscles regularly", "Drink lots of coffee", "Buy a new chair", "Work standing up"], correctIndex: 0, explanation: "You should 'thoroughly stretch your stiff muscles regularly and take short, brisk walking breaks'." },
        { question: "What should you do if you hurt your knee?", options: ["Rest and apply ice", "Keep running", "Take a hot shower", "Go to sleep"], correctIndex: 0, explanation: "You should 'immediately rest the affected area, apply a cold ice pack to rapidly reduce the swelling'." },
        { question: "What is the best way to avoid serious injuries?", options: ["Listening to your body", "Never exercising", "Running every day", "Eating healthy food"], correctIndex: 0, explanation: "The text concludes 'patiently listening to your body's subtle warning signals is undisputedly the absolute best way to avoid sustaining serious... injuries'." }
      ]
    }
  },
  "casa": {
    level1: {
      textEn: "My house may be relatively small in size, but it is undeniably very comfortable, warm, and absolutely perfect for my entire family. It currently features two bright, naturally lit bedrooms, a remarkably spacious kitchen filled with modern appliances, and a delightfully cozy living room where we spend most of our evenings. I have the privilege of sleeping in my very own bedroom, and I take great pride in making sure to perfectly make my bed every single morning before I ever head down for breakfast. At the end of a long day, my family usually gathers around the large wooden table to eat a delicious hot dinner together in the kitchen, where we excitedly talk about everything that happened during our day. Keeping our beloved house clean and tidy is truly a collective team effort that requires everyone's participation. For example, every Sunday morning, I always happily help my hardworking mother sweep the dusty floor, meticulously dust the crowded bookshelves, and carefully take out the heavy trash so we can confidently start the new week with a sparkling clean home.",
      textPt: "Minha casa pode ser relativamente pequena em tamanho, mas é inegavelmente muito confortável, acolhedora e absolutamente perfeita para toda a minha família. Atualmente, ela possui dois quartos iluminados naturalmente, uma cozinha notavelmente espaçosa cheia de eletrodomésticos modernos e uma sala de estar deliciosamente aconchegante, onde passamos a maior parte das nossas noites. Tenho o privilégio de dormir no meu próprio quarto e tenho muito orgulho de garantir que arrumo minha cama perfeitamente todas as manhãs antes de descer para o café da manhã. No final de um longo dia, minha família geralmente se reúne ao redor da grande mesa de madeira para comer um delicioso jantar quente juntos na cozinha, onde conversamos animadamente sobre tudo o que aconteceu durante o nosso dia. Manter nossa amada casa limpa e arrumada é verdadeiramente um esforço coletivo de equipe que requer a participação de todos. Por exemplo, todo domingo de manhã, eu sempre ajudo alegremente minha mãe trabalhadora a varrer o chão empoeirado, tirar meticulosamente o pó das estantes lotadas e tirar com cuidado o lixo pesado para que possamos começar a nova semana com confiança, com uma casa brilhantemente limpa.",
      questions: [
        { question: "How many bedrooms does the house have?", options: ["Two", "Three", "One", "Four"], correctIndex: 0, explanation: "The text says 'It currently features two bright, naturally lit bedrooms'." },
        { question: "What does the author do every morning?", options: ["Makes the bed", "Cooks breakfast", "Washes the dishes", "Sweeps the floor"], correctIndex: 0, explanation: "They say they 'make sure to perfectly make my bed every single morning'." },
        { question: "Where does the family eat dinner?", options: ["In the kitchen", "In the living room", "In the garden", "In the bedroom"], correctIndex: 0, explanation: "They gather to eat dinner 'together in the kitchen'." },
        { question: "What chores does the author do on Sundays?", options: ["Sweep the floor and take out the trash", "Clean the windows", "Wash the car", "Iron the clothes"], correctIndex: 0, explanation: "They help 'sweep the dusty floor, meticulously dust the crowded bookshelves, and carefully take out the heavy trash'." }
      ]
    },
    level2: {
      textEn: "Consistently maintaining a spectacularly clean and deeply welcoming home requires unwavering dedication and highly coordinated teamwork from absolutely everyone living under its roof. Every single spring, without fail, we collectively dedicate an entire, exhausting weekend to successfully execute a comprehensive deep cleaning of the entire house, thoroughly scrubbing everything from the dark attic straight down to the damp basement. During this intense process, I am usually heavily responsible for thoroughly vacuuming all the heavy, dust-filled carpets and carefully dusting the fragile, delicate antique furniture located in the main living room. On the other hand, my older sister strongly prefers to independently handle the monumental task of doing the family's laundry; she genuinely likes to steam iron the wrinkled clothes and fold them neatly and methodically into the wooden dressers' drawers. Furthermore, having a spacious, designated garage attached to the house immensely helps us keep our messy outdoor space and various mechanical tools perfectly organized and out of sight. Meanwhile, our beautiful, lush green garden in the backyard consistently provides a much-needed, tranquil relaxing area for all of us to completely unwind and destress on the quiet weekends.",
      textPt: "Manter consistentemente uma casa espetacularmente limpa e profundamente acolhedora exige dedicação inabalável e trabalho em equipe altamente coordenado de absolutamente todos que vivem sob seu teto. Toda primavera, sem falta, dedicamos coletivamente um fim de semana inteiro e exaustivo para executar com sucesso uma limpeza profunda abrangente em toda a casa, esfregando tudo, desde o sótão escuro até o porão úmido. Durante este intenso processo, geralmente sou o maior responsável por aspirar completamente todos os tapetes pesados e cheios de poeira e limpar cuidadosamente os frágeis e delicados móveis antigos localizados na sala principal. Por outro lado, minha irmã mais velha prefere fortemente lidar de forma independente com a tarefa monumental de lavar a roupa da família; ela gosta genuinamente de passar a vapor as roupas amassadas e dobrá-las de forma organizada e metódica nas gavetas das cômodas de madeira. Além disso, ter uma garagem espaçosa e designada anexa à casa nos ajuda imensamente a manter nosso espaço externo bagunçado e várias ferramentas mecânicas perfeitamente organizadas e fora de vista. Enquanto isso, nosso lindo e exuberante jardim verde no quintal fornece consistentemente uma área de relaxamento tranquila e muito necessária para que todos nós possamos relaxar e desestressar completamente nos fins de semana tranquilos.",
      questions: [
        { question: "When does the family do a deep cleaning?", options: ["Every spring", "Every winter", "Once a month", "Every weekend"], correctIndex: 0, explanation: "They dedicate an entire weekend 'Every single spring, without fail'." },
        { question: "What chores does the author usually do?", options: ["Vacuum the carpets and dust the furniture", "Iron and fold clothes", "Mow the lawn", "Wash the dishes"], correctIndex: 0, explanation: "They are responsible for 'vacuuming all the heavy, dust-filled carpets and carefully dusting the fragile, delicate antique furniture'." },
        { question: "What does the sister prefer to do?", options: ["Iron the clothes and fold the laundry", "Clean the windows", "Cook dinner", "Water the plants"], correctIndex: 0, explanation: "She prefers 'to independently handle the monumental task of doing the family's laundry; she genuinely likes to steam iron the wrinkled clothes and fold them'." },
        { question: "What provides a relaxing area for weekends?", options: ["The garden", "The living room", "The balcony", "The garage"], correctIndex: 0, explanation: "The text says 'our beautiful, lush green garden in the backyard consistently provides a much-needed, tranquil relaxing area'." }
      ]
    }
  },
  "casa2": {
    level1: {
      textEn: "Without a doubt, my absolute favorite room in our entire large house is the exceptionally bright and welcoming living room. We are so lucky to have a massive, incredibly soft blue couch right in the center, alongside a huge flat-screen TV securely mounted on the opposite wall. Every evening immediately after we finish eating a delicious dinner, I really love to just sit back on the plush couch, completely relax my tired muscles, and excitedly watch thrilling action movies with my entire family. Sometimes, usually on early Saturday mornings, my energetic father carefully mops the wooden floor using a highly specialized, great-smelling cleaner just to ensure it keeps looking shiny, spotless, and brand new. In addition to the main seating area, we also have a wonderful, small open balcony directly connected to the living room by a sliding glass door. In the breezy late afternoons, we frequently like to stand out on the balcony together because we can easily see the bustling street below and peacefully watch the colorful cars and busy neighbors pass by.",
      textPt: "Sem dúvida, o meu cômodo favorito absoluto em toda a nossa grande casa é a sala de estar, excepcionalmente iluminada e acolhedora. Temos muita sorte de ter um sofá azul enorme e incrivelmente macio bem no centro, ao lado de uma enorme TV de tela plana montada com segurança na parede oposta. Todas as noites, imediatamente depois de terminarmos de comer um jantar delicioso, eu adoro recostar no sofá macio, relaxar completamente meus músculos cansados e assistir animadamente a emocionantes filmes de ação com toda a minha família. Às vezes, geralmente nas madrugadas de sábado, meu enérgico pai esfrega cuidadosamente o piso de madeira usando um limpador altamente especializado e com ótimo cheiro apenas para garantir que ele continue parecendo brilhante, impecável e novo em folha. Além da área de estar principal, também temos uma maravilhosa e pequena varanda aberta diretamente conectada à sala de estar por uma porta de vidro deslizante. No final das tardes arejadas, gostamos frequentemente de ficar juntos na varanda, pois podemos ver facilmente a rua movimentada lá embaixo e observar pacificamente os carros coloridos e vizinhos ocupados passando.",
      questions: [
        { question: "What is the author's favorite room?", options: ["The living room", "The bedroom", "The kitchen", "The bathroom"], correctIndex: 0, explanation: "They state 'my absolute favorite room in our entire large house is the exceptionally bright and welcoming living room'." },
        { question: "What color is the couch?", options: ["Blue", "Red", "Black", "White"], correctIndex: 0, explanation: "They have a 'massive, incredibly soft blue couch'." },
        { question: "What does the father do to the floor?", options: ["He mops it", "He sweeps it", "He paints it", "He ignores it"], correctIndex: 0, explanation: "The father 'carefully mops the wooden floor using a highly specialized, great-smelling cleaner'." },
        { question: "What can they see from the balcony?", options: ["The street", "The garden", "The ocean", "The neighbors"], correctIndex: 0, explanation: "From the balcony 'we can easily see the bustling street below and peacefully watch the colorful cars'." }
      ]
    },
    level2: {
      textEn: "Executing effective and comprehensive household maintenance goes significantly beyond simply performing the basic weekly cleaning routines. As a responsible homeowner, you essentially have to constantly and proactively ensure that absolutely everything within the physical structure of the building functions properly and safely. For instance, just yesterday, I spent the entire, exhausting afternoon aggressively washing all the terribly dirty exterior glass windows and then carefully watering the dozens of fragile potted plants that decorate our sunny, south-facing balcony. Looking ahead to tomorrow, my father has deliberately planned a notoriously busy schedule for himself: he will diligently mow the overgrown front lawn using the heavy lawnmower, and afterward, he will grab a tall aluminum ladder to meticulously check the high wooden ceiling for any early signs of dangerous water leaks before the harsh rainy season inevitably begins. By consistently and rigorously keeping up with these physically demanding chores, a homeowner successfully prevents much bigger, severely damaging, and outrageously expensive structural problems from unexpectedly occurring in the distant future.",
      textPt: "A execução de uma manutenção doméstica eficaz e abrangente vai significativamente além da simples realização das rotinas básicas de limpeza semanais. Como proprietário responsável, você essencialmente tem que garantir, de forma constante e proativa, que absolutamente tudo dentro da estrutura física do prédio funcione de maneira adequada e segura. Por exemplo, só ontem, passei a tarde inteira e exaustiva lavando agressivamente todas as janelas de vidro exteriores terrivelmente sujas e depois regando cuidadosamente as dezenas de plantas frágeis em vasos que decoram a nossa varanda ensolarada e voltada para o sul. Olhando para amanhã, meu pai planejou deliberadamente uma agenda notoriamente ocupada para si mesmo: ele cortará diligentemente o gramado da frente coberto de vegetação usando o pesado cortador de grama e, depois, pegará uma escada alta de alumínio para verificar meticulosamente o alto teto de madeira em busca de quaisquer sinais iniciais de vazamentos perigosos de água antes que a dura estação das chuvas comece inevitavelmente. Ao se manter consistente e rigorosamente em dia com essas tarefas fisicamente exigentes, o proprietário evita com sucesso que problemas estruturais muito maiores, severamente danosos e absurdamente caros ocorram inesperadamente no futuro distante.",
      questions: [
        { question: "What did the author do yesterday afternoon?", options: ["Washed the windows and watered plants", "Mowed the lawn", "Fixed the ceiling", "Painted the balcony"], correctIndex: 0, explanation: "They spent the afternoon 'washing all the terribly dirty exterior glass windows and then carefully watering the dozens of fragile potted plants'." },
        { question: "What will the father do tomorrow?", options: ["Mow the lawn and check the ceiling", "Buy new plants", "Clean the garage", "Wash the car"], correctIndex: 0, explanation: "He will 'diligently mow the overgrown front lawn... and afterward, he will grab a tall aluminum ladder to meticulously check the high wooden ceiling'." },
        { question: "What is the ceiling made of?", options: ["Wood", "Concrete", "Glass", "Metal"], correctIndex: 0, explanation: "It is described as a 'wooden ceiling'." },
        { question: "Why is keeping up with chores important?", options: ["It prevents bigger problems in the future", "It makes the neighbors happy", "It is good exercise", "It is required by law"], correctIndex: 0, explanation: "It 'prevents much bigger, severely damaging, and outrageously expensive structural problems from unexpectedly occurring'." }
      ]
    }
  },
  "hobbies": {
    level1: {
      textEn: "On most weekends, especially when we don't have to go to school, I usually have a tremendous amount of free time to dedicate to doing the creative things I really enjoy. I absolutely love to spend many long, quiet hours reading thrilling adventure books while lying comfortably on the soft bed in my private room. My energetic younger brother is very different from me; he intensely dislikes reading and instead prefers to loudly play fast-paced video games on the massive TV in the living room while constantly chatting with his school friends online. Occasionally, when it is raining heavily outside and we are completely stuck indoors, we sit closely together and happily draw incredibly colorful, imaginative pictures at the wide kitchen table. Engaging in personal hobbies is undeniably a great and productive way to deeply relax your tired mind and playfully learn brand-new skills without ever feeling the heavy pressure and stress that usually comes from school or work assignments.",
      textPt: "Na maioria dos fins de semana, especialmente quando não temos que ir à escola, eu geralmente tenho uma tremenda quantidade de tempo livre para dedicar às coisas criativas que eu realmente gosto. Adoro absolutamente passar muitas horas longas e tranquilas lendo livros de aventura emocionantes deitado confortavelmente na cama macia do meu quarto privado. Meu irmão mais novo, cheio de energia, é muito diferente de mim; ele não gosta nem um pouco de ler e, em vez disso, prefere jogar jogos de videogame em ritmo acelerado na enorme TV da sala de estar enquanto conversa constantemente online com os amigos da escola. Ocasionalmente, quando está chovendo muito lá fora e ficamos totalmente presos dentro de casa, sentamo-nos próximos uns dos outros e alegremente desenhamos imagens incrivelmente coloridas e imaginativas na ampla mesa da cozinha. O envolvimento com hobbies pessoais é inegavelmente uma maneira excelente e produtiva de relaxar profundamente a mente cansada e aprender de forma lúdica habilidades totalmente novas, sem nunca sentir a forte pressão e o estresse que geralmente acompanham as tarefas escolares ou profissionais.",
      questions: [
        { question: "What does the author love to do in their room?", options: ["Read books", "Play video games", "Sleep", "Listen to music"], correctIndex: 0, explanation: "They 'absolutely love to spend many long, quiet hours reading thrilling adventure books'." },
        { question: "What is the brother's hobby?", options: ["Playing video games", "Drawing pictures", "Reading books", "Playing soccer"], correctIndex: 0, explanation: "The brother 'prefers to loudly play fast-paced video games on the massive TV'." },
        { question: "What do they do together at the table?", options: ["Draw pictures", "Eat dinner", "Do homework", "Play cards"], correctIndex: 0, explanation: "They 'happily draw incredibly colorful, imaginative pictures at the wide kitchen table'." },
        { question: "According to the text, why are hobbies great?", options: ["They help you relax and learn", "They make you rich", "They are competitive", "They are mandatory"], correctIndex: 0, explanation: "Hobbies are a way to 'deeply relax your tired mind and playfully learn brand-new skills'." }
      ]
    },
    level2: {
      textEn: "Deliberately developing a challenging, highly creative hobby can drastically and positively improve your overall mental health, emotional resilience, and daily focus in profound ways. A few years ago, shortly after feeling completely burned out from the relentless demands of my stressful corporate work, I firmly decided to take up the complex art of knitting as a uniquely therapeutic activity. Admittedly, it was incredibly frustrating at first because my inexperienced hands kept clumsily dropping vital stitches, but through sheer perseverance, I can now confidently and quickly knit wonderfully warm, intricately designed sweaters for my entire extended family. My best friend, on the other hand, is extremely keen on the painstaking hobby of collecting incredibly rare, historical postage stamps, an intellectual pursuit which rigidly requires meticulous patience, an eye for tiny details, and deep historical research. Ultimately, whatever specific interest or passion you eventually choose to pursue with your limited free time, engaging hobbies consistently provide a highly valuable and undeniably necessary psychological escape from our perpetually busy, exhausting, and overwhelmingly digital-driven modern lives.",
      textPt: "Desenvolver deliberadamente um hobby desafiador e altamente criativo pode melhorar de forma drástica e positiva sua saúde mental geral, resiliência emocional e foco diário de maneiras profundas. Alguns anos atrás, logo após me sentir completamente esgotado devido às demandas implacáveis do meu estressante trabalho corporativo, decidi firmemente assumir a complexa arte do tricô como uma atividade singularmente terapêutica. Confesso que foi incrivelmente frustrante no início, porque minhas mãos inexperientes continuavam deixando cair pontos vitais de forma desajeitada, mas, por meio de pura perseverança, agora posso tricotar com confiança e rapidez blusas maravilhosamente quentes e com design complexo para toda a minha família. Meu melhor amigo, por outro lado, é extremamente apaixonado pelo meticuloso hobby de colecionar selos postais históricos incrivelmente raros, uma busca intelectual que exige rigorosamente paciência minuciosa, olho para pequenos detalhes e profunda pesquisa histórica. Em última análise, independentemente do interesse ou paixão específica que você acabe escolhendo seguir com seu tempo livre limitado, hobbies envolventes fornecem consistentemente uma fuga psicológica altamente valiosa e inegavelmente necessária de nossas vidas modernas perpetuamente ocupadas, exaustivas e predominantemente digitais.",
      questions: [
        { question: "What benefit can a creative hobby provide?", options: ["It can improve your mental health", "It can increase your salary", "It makes you famous", "It replaces physical exercise"], correctIndex: 0, explanation: "It can 'drastically and positively improve your overall mental health, emotional resilience, and daily focus'." },
        { question: "What hobby did the author take up?", options: ["Knitting", "Stamp collecting", "Painting", "Gardening"], correctIndex: 0, explanation: "They decided to 'take up the complex art of knitting as a uniquely therapeutic activity'." },
        { question: "What is the best friend keen on doing?", options: ["Collecting rare stamps", "Knitting sweaters", "Playing video games", "Traveling"], correctIndex: 0, explanation: "The friend is 'extremely keen on the painstaking hobby of collecting incredibly rare, historical postage stamps'." },
        { question: "What do hobbies provide an escape from?", options: ["Our busy digital lives", "Physical pain", "Financial problems", "Family gatherings"], correctIndex: 0, explanation: "They provide an escape 'from our perpetually busy, exhausting, and overwhelmingly digital-driven modern lives'." }
      ]
    }
  },
  "esportes": {
    level1: {
      textEn: "Because I truly love being active and spending time outdoors, I always make sure to play competitive soccer with my neighborhood friends every single Tuesday evening without fail. We practice a lot during the week, and I honestly think we have managed to build a really good, highly coordinated team right now. Sprinting back and forth across the massively large, bright green grass field for an hour is undeniably very tiring on the legs, but successfully scoring a beautiful, unexpected goal makes all of us feel incredibly happy, energized, and deeply proud of our hard work. After the long, exhausting match finally finishes under the stadium lights, we are usually extremely sweaty and very thirsty. Consequently, we sit together on the cold benches and eagerly drink a whole lot of refreshing, icy cold water while excitedly discussing the game's best moments. Ultimately, regularly engaging in fun team sports is not only an excellent, social way to have an amazing time, but it is also exceptionally good for maintaining your long-term physical health.",
      textPt: "Como eu realmente amo ser ativo e passar tempo ao ar livre, sempre me certifico de jogar futebol competitivo com meus amigos do bairro toda terça-feira à noite, sem falta. Nós praticamos muito durante a semana, e honestamente acho que conseguimos construir um time muito bom e altamente coordenado no momento. Correr de um lado para o outro no enorme campo de grama verde e brilhante por uma hora é inegavelmente muito cansativo para as pernas, mas marcar com sucesso um belo e inesperado gol faz com que todos nos sintamos incrivelmente felizes, cheios de energia e profundamente orgulhosos do nosso trabalho árduo. Depois que a longa e exaustiva partida finalmente termina sob as luzes do estádio, geralmente estamos extremamente suados e com muita sede. Consequentemente, sentamos juntos nos bancos frios e bebemos avidamente muita água gelada e refrescante enquanto discutimos com entusiasmo os melhores momentos do jogo. Em última análise, participar regularmente de divertidos esportes coletivos não é apenas uma excelente e social maneira de se divertir, mas também é excepcionalmente bom para manter a sua saúde física a longo prazo.",
      questions: [
        { question: "When do they play soccer?", options: ["Every Tuesday", "Every weekend", "Every Monday", "Once a month"], correctIndex: 0, explanation: "They play 'every single Tuesday evening without fail'." },
        { question: "What makes them very happy?", options: ["Scoring a goal", "Running on the field", "Drinking water", "Winning a trophy"], correctIndex: 0, explanation: "Successfully 'scoring a beautiful, unexpected goal makes all of us feel incredibly happy'." },
        { question: "How do they feel after the match?", options: ["Very thirsty", "Very angry", "Very bored", "Very cold"], correctIndex: 0, explanation: "They are 'usually extremely sweaty and very thirsty'." },
        { question: "What is the conclusion about sports?", options: ["They are good for your health", "They are too tiring", "They are only for professionals", "They are dangerous"], correctIndex: 0, explanation: "The text states it 'is also exceptionally good for maintaining your long-term physical health'." }
      ]
    },
    level2: {
      textEn: "Actively participating in highly competitive, professional sports at the global level requires vastly more than just possessing incredible natural raw talent; it fundamentally demands intense, unwavering daily discipline and the brilliant strategic guidance of a truly great, experienced coach. In order to consistently and successfully perform at the absolute highest possible competitive level, these elite professional athletes must ruthlessly dedicate themselves to going to the gym every single day, lifting heavy weights, and meticulously maintaining a very strict, highly calculated, nutrient-rich diet that optimizes their physical performance. Furthermore, during a high-stakes professional tennis match, for example, an eagle-eyed, officially certified referee is always present on the court to strictly ensure that all of the sport's complex, nuanced rules are followed fairly and equally by both exhausted players. However, even if a dedicated athlete ultimately loses a remarkably difficult, grueling match after giving their absolute best effort, the challenging emotional experience itself effectively builds profound psychological resilience and incredibly strong personal character over time. Ultimately, the true, legendary champions of any sport are always the ones who humbly know exactly how to clinically analyze their painful mistakes, adapt their strategy, and genuinely learn from their most devastating failures.",
      textPt: "Participar ativamente de esportes profissionais e altamente competitivos em nível global requer muito mais do que apenas possuir um incrível talento natural bruto; fundamentalmente exige intensa e inabalável disciplina diária e a brilhante orientação estratégica de um técnico verdadeiramente grande e experiente. A fim de atuar consistente e com sucesso no mais alto nível competitivo possível, esses atletas profissionais de elite devem dedicar-se impiedosamente a ir à academia todos os dias, levantando pesos pesados e mantendo meticulosamente uma dieta muito rigorosa, altamente calculada e rica em nutrientes que otimiza seu desempenho físico. Além disso, durante uma partida de tênis profissional de alto risco, por exemplo, um árbitro oficial e atento está sempre presente na quadra para garantir rigorosamente que todas as complexas e sutis regras do esporte sejam seguidas de forma justa e igual por ambos os jogadores exaustos. No entanto, mesmo que um atleta dedicado acabe perdendo uma partida notavelmente difícil e extenuante após dar seu esforço máximo, a desafiadora experiência emocional em si efetivamente constrói profunda resiliência psicológica e um caráter pessoal incrivelmente forte com o tempo. Em última análise, os verdadeiros e lendários campeões de qualquer esporte são sempre aqueles que, com humildade, sabem exatamente como analisar clinicamente seus erros dolorosos, adaptar sua estratégia e aprender genuinamente com seus fracassos mais devastadores.",
      questions: [
        { question: "What do professional sports require?", options: ["Intense discipline and a great coach", "Only natural talent", "A lot of free time", "Expensive equipment"], correctIndex: 0, explanation: "They require 'intense, unwavering daily discipline and the brilliant strategic guidance of a truly great, experienced coach'." },
        { question: "What must athletes do to perform at the highest level?", options: ["Go to the gym daily and maintain a strict diet", "Rest constantly", "Eat lots of sweets", "Ignore the coach"], correctIndex: 0, explanation: "They must 'dedicate themselves to going to the gym every single day... and meticulously maintaining a very strict... nutrient-rich diet'." },
        { question: "What is the role of the referee?", options: ["To ensure rules are followed fairly", "To coach the players", "To sell tickets", "To play in the match"], correctIndex: 0, explanation: "A referee is present 'to strictly ensure that all of the sport's complex, nuanced rules are followed fairly'." },
        { question: "What do true champions know how to do?", options: ["Learn from failure", "Always win", "Cheat the referee", "Avoid the gym"], correctIndex: 0, explanation: "True champions are the ones who 'know exactly how to clinically analyze their painful mistakes... and genuinely learn from their most devastating failures'." }
      ]
    }
  },
  "supermercado": {
    level1: {
      textEn: "Every Friday afternoon, right after I finish my long week of work, I have a very strict personal routine where I confidently drive to the massive, brightly lit supermarket located conveniently near my house. As soon as I arrive at the large automatic doors, I grab a shiny metal shopping cart and slowly begin to walk down the endless, colorful aisles to carefully find absolutely everything I need for the upcoming week. I usually make sure to buy freshly baked bread from the bakery section, several cartons of ice-cold milk from the dairy aisle, and a large variety of sweet, juicy fruit like red apples and yellow bananas to snack on. When my spacious cart is finally full of groceries, I go straight to the friendly cashier sitting at the busy front of the store so I can pay for all my items using my credit card. Before leaving the noisy store and walking back to my car, I always make a point to check the long printed paper receipt very carefully to make absolutely sure that the final scanned price is entirely correct and I wasn't overcharged.",
      textPt: "Toda sexta-feira à tarde, logo após eu terminar minha longa semana de trabalho, tenho uma rotina pessoal muito rígida na qual dirijo confiante para o supermercado gigantesco e bem iluminado, convenientemente localizado perto da minha casa. Assim que chego às grandes portas automáticas, pego um carrinho de compras de metal brilhante e começo a andar lentamente pelos corredores coloridos e intermináveis para encontrar cuidadosamente absolutamente tudo o que preciso para a semana que se inicia. Costumo me certificar de comprar pão recém-assado na seção da padaria, várias caixas de leite gelado no corredor de laticínios e uma grande variedade de frutas doces e suculentas, como maçãs vermelhas e bananas amarelas, para beliscar. Quando meu espaçoso carrinho finalmente está cheio de mantimentos, vou direto para a simpática operadora de caixa sentada na movimentada frente da loja para que eu possa pagar por todos os meus itens usando meu cartão de crédito. Antes de sair da loja barulhenta e voltar para o meu carro, sempre faço questão de verificar o longo recibo de papel impresso com muito cuidado para ter absoluta certeza de que o preço final escaneado está totalmente correto e eu não fui cobrado a mais.",
      questions: [
        { question: "When does the author go to the supermarket?", options: ["Every Friday", "Every Sunday", "Every morning", "Once a month"], correctIndex: 0, explanation: "They go 'Every Friday afternoon'." },
        { question: "What items does the author mention buying?", options: ["Bread, milk, and fruit", "Meat and vegetables", "Clothes and shoes", "Candy and soda"], correctIndex: 0, explanation: "They buy 'freshly baked bread... ice-cold milk... and a large variety of sweet, juicy fruit'." },
        { question: "Who does the author go to when the cart is full?", options: ["The cashier", "The manager", "A security guard", "A friend"], correctIndex: 0, explanation: "They go 'straight to the friendly cashier sitting at the busy front of the store'." },
        { question: "Why do they check the receipt?", options: ["To make sure the price is correct", "To see if they won a prize", "To find a discount code", "To keep it for taxes"], correctIndex: 0, explanation: "They check the receipt 'to make absolutely sure that the final scanned price is entirely correct'." }
      ]
    },
    level2: {
      textEn: "Navigating your way effectively through a massive, labyrinth-like modern grocery store during peak shopping hours can easily become an extremely overwhelming and deeply frustrating experience if you blatantly fail to take the essential time to write down a highly detailed, categorized shopping list beforehand. Last weekend, after completely emptying my kitchen pantry, I firmly decided it was finally time to comprehensively stock up on tons of healthy, organic vegetables and various low-fat dairy products in order to strictly maintain my new, ambitious health-conscious diet. Feeling determined, I confidently walked right into the famously busy, aromatic bakery section, only to devastatingly discover that a previous rush of hungry customers had completely sold out the store's entire stock of my absolute favorite artisanal whole-wheat bread. Because it happened to be a terribly busy Saturday afternoon, I unfortunately ended up standing in a very long, agonizingly slow-moving queue at the main checkout counter for almost half an hour. However, the tedious wait ultimately proved to be well worth it because the remarkably friendly and observant cashier miraculously found a great, totally unexpected digital discount bargain for some of my far more expensive imported items. Ultimately, the valuable lesson learned is that being meticulously and relentlessly organized before stepping foot out the door to do your grocery shopping effortlessly saves you a highly significant amount of both precious time and hard-earned money.",
      textPt: "Navegar de forma eficaz por um enorme supermercado moderno que parece um labirinto durante os horários de pico de compras pode facilmente se tornar uma experiência extremamente avassaladora e profundamente frustrante se você não reservar o tempo essencial para escrever com antecedência uma lista de compras altamente detalhada e categorizada. No último fim de semana, depois de esvaziar completamente a despensa da minha cozinha, decidi firmemente que era finalmente a hora de me abastecer de forma abrangente com toneladas de vegetais orgânicos e saudáveis e vários produtos lácteos com baixo teor de gordura a fim de manter rigorosamente minha nova e ambiciosa dieta focada na saúde. Sentindo-me determinado, caminhei confiantemente direto para a seção da padaria notoriamente movimentada e aromática, apenas para descobrir de forma devastadora que uma onda anterior de clientes famintos havia esgotado completamente o estoque inteiro do meu pão integral artesanal favorito na loja. Por ser um sábado à tarde terrivelmente movimentado, infelizmente acabei ficando em uma fila muito longa e agonizantemente lenta no caixa principal por quase meia hora. No entanto, a espera tediosa acabou provando valer a pena porque o caixa notavelmente amigável e observador encontrou milagrosamente uma excelente e totalmente inesperada barganha de desconto digital para alguns dos meus itens importados muito mais caros. No final das contas, a valiosa lição aprendida é que ser meticulosamente e incansavelmente organizado antes de pisar fora de casa para fazer as compras no supermercado economiza sem esforço uma quantidade altamente significativa tanto de tempo precioso quanto de dinheiro arduamente ganho.",
      questions: [
        { question: "What can make grocery shopping overwhelming?", options: ["Not having a list", "Buying too much bread", "Going on a weekend", "Using a shopping cart"], correctIndex: 0, explanation: "It can be overwhelming 'if you blatantly fail to take the essential time to write down a highly detailed, categorized shopping list'." },
        { question: "What did the author want to stock up on?", options: ["Vegetables and dairy products", "Meat and fish", "Fruit and juice", "Sweets and bread"], correctIndex: 0, explanation: "They wanted to stock up on 'healthy, organic vegetables and various low-fat dairy products'." },
        { question: "What happened in the bakery section?", options: ["They had sold out of the author's favorite bread", "They found a great bargain", "The line was too long", "They bought a lot of cakes"], correctIndex: 0, explanation: "They discovered that they 'had completely sold out the store's entire stock of my absolute favorite artisanal whole-wheat bread'." },
        { question: "What is the benefit of being organized?", options: ["It saves time and money", "It helps you find the bakery", "It makes the queue shorter", "It gets you free groceries"], correctIndex: 0, explanation: "Being organized 'effortlessly saves you a highly significant amount of both precious time and hard-earned money'." }
      ]
    }
  }
};

function injectData(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');

  for (const [id, reading] of Object.entries(data)) {
    const scenarioStart = content.indexOf(`id: "${id}"`);
    if (scenarioStart === -1) continue;

    let nextId = content.indexOf('id: "', scenarioStart + 10);
    if (nextId === -1) nextId = content.length;
    let section = content.slice(scenarioStart, nextId);

    const readingStr = 'reading: ' + JSON.stringify(reading, null, 6);
    const readingStart = section.indexOf('    reading: {');
    const vocabStart = section.indexOf('    vocabulary: [');
    
    if (readingStart !== -1 && vocabStart !== -1 && vocabStart > readingStart) {
      section = section.slice(0, readingStart) + '    ' + readingStr + ',\n' + section.slice(vocabStart);
    }

    content = content.slice(0, scenarioStart) + section + content.slice(nextId);
  }

  fs.writeFileSync(filePath, content);
}

injectData('./data/scenarios1.ts');
console.log("Injected SUPER Extended Reading into scenarios1.ts with safer AST logic");
