const fs = require('fs');

const data = {
  "compras": {
    level1: {
      textEn: "I absolutely love spending my free time shopping for new, fashionable clothes and completely updating my personal wardrobe every single season. Usually, I strongly prefer to drive down to the massive, multi-level shopping mall on early Saturday mornings right after I finish eating my breakfast. I choose this specific time because the mall is delightfully quiet, peaceful, and not overly crowded with noisy shoppers. Last week, while casually walking past the bright windows of my favorite clothing store, I suddenly found a incredibly beautiful, highly stylish leather jacket proudly displayed on a mannequin. I immediately fell in love with it and wanted to buy it. However, when I closely checked the tiny price tag hidden on the sleeve, I quickly realized it was way too expensive and completely out of my current monthly budget. So, I ultimately decided to be much more practical with my money and instead bought a much cheaper, yet very comfortable casual shirt and a perfectly fitting pair of dark blue jeans. Saving my hard-earned money is always very important to me, so I make it a strict habit to look carefully for great promotional discounts and massive seasonal sales before I confidently buy anything new.",
      textPt: "Eu absolutamente amo passar meu tempo livre comprando roupas novas e da moda e atualizando completamente meu guarda-roupa pessoal a cada estação. Geralmente, prefiro muito dirigir até o enorme shopping center de vários andares nas manhãs de sábado, logo após terminar o café da manhã. Eu escolho este horário específico porque o shopping é deliciosamente tranquilo, pacífico e não excessivamente lotado de compradores barulhentos. Na semana passada, enquanto passava casualmente pelas vitrines iluminadas da minha loja de roupas favorita, de repente encontrei uma jaqueta de couro incrivelmente bonita e muito estilosa, orgulhosamente exibida em um manequim. Eu imediatamente me apaixonei por ela e queria comprá-la. No entanto, quando olhei de perto a pequena etiqueta de preço escondida na manga, percebi rapidamente que era cara demais e estava completamente fora do meu orçamento mensal atual. Então, acabei decidindo ser muito mais prático com meu dinheiro e, em vez disso, comprei uma camisa casual muito mais barata, mas muito confortável, e uma calça jeans azul escura com um caimento perfeito. Economizar meu dinheiro suado é sempre muito importante para mim, então tenho o hábito estrito de procurar cuidadosamente por ótimos descontos promocionais e enormes vendas sazonais antes de comprar com confiança qualquer coisa nova.",
      questions: [
        { question: "Why does the author prefer to go to the mall on Saturday mornings?", options: ["Because the mall is quiet", "Because that is when new clothes arrive", "Because they work on Saturday afternoons", "Because the discounts are better"], correctIndex: 0, explanation: "They go on Saturday mornings 'because the mall is delightfully quiet, peaceful, and not overly crowded'." },
        { question: "Why didn't the author buy the jacket?", options: ["It was too expensive", "It was the wrong color", "It did not fit well", "They preferred the shirt"], correctIndex: 0, explanation: "They didn't buy the jacket because 'it was way too expensive and completely out of my current monthly budget'." },
        { question: "What did the author ultimately purchase?", options: ["A shirt and blue jeans", "Only a pair of blue jeans", "A jacket and a shirt", "Shoes and a shirt"], correctIndex: 0, explanation: "They decided to buy 'a much cheaper... casual shirt and a perfectly fitting pair of dark blue jeans'." },
        { question: "What does the author always look for?", options: ["Discounts and sales", "Expensive jackets", "Quiet malls", "Saturday mornings"], correctIndex: 0, explanation: "They say 'I make it a strict habit to look carefully for great promotional discounts and massive seasonal sales'." }
      ]
    },
    level2: {
      textEn: "The highly lucrative, global retail industry relies exceptionally heavily on rapidly changing seasonal trends to artificially drive massive consumer sales and boost continuous corporate profits. Unfortunately, modern consumers are constantly and aggressively encouraged by relentless advertising campaigns to update their wardrobes as frequently as possible, which directly and undeniably leads to the highly problematic global phenomenon known as fast fashion. Although finding a surprisingly cheap bargain is often thrilling and satisfying in the short term, we as a society must seriously consider the severe, devastating long-term environmental impact of mass-producing millions of cheap, low-quality garments every single year. Fortunately, there are viable alternatives available to conscious shoppers. I recently discovered a remarkably charming vintage shop hidden in my historic neighborhood that exclusively sells high-quality, pre-owned leather goods and incredibly well-made classic clothing from previous decades. Investing intelligently in highly durable, timeless items rather than continuously buying disposable, poorly made fast fashion is undeniably a much more sustainable, ecologically responsible, and financially wise approach to modern, everyday shopping.",
      textPt: "O altamente lucrativo setor de varejo global depende excepcionalmente forte das tendências sazonais em rápida mudança para impulsionar artificialmente as vendas maciças ao consumidor e aumentar os lucros corporativos contínuos. Infelizmente, os consumidores modernos são constante e agressivamente incentivados por campanhas publicitárias implacáveis a atualizar seus guarda-roupas com a maior frequência possível, o que leva direta e inegavelmente ao fenômeno global altamente problemático conhecido como moda rápida (fast fashion). Embora encontrar uma pechincha surpreendentemente barata seja muitas vezes emocionante e satisfatório no curto prazo, nós, como sociedade, devemos considerar seriamente o grave e devastador impacto ambiental a longo prazo de produzir em massa milhões de roupas baratas e de baixa qualidade a cada ano. Felizmente, existem alternativas viáveis disponíveis para compradores conscientes. Recentemente, descobri um brechó notavelmente charmoso escondido em meu bairro histórico que vende exclusivamente artigos de couro usados de alta qualidade e roupas clássicas incrivelmente bem feitas de décadas anteriores. Investir inteligentemente em itens altamente duráveis e atemporais, em vez de comprar continuamente moda rápida descartável e mal feita, é inegavelmente uma abordagem muito mais sustentável, ecologicamente responsável e financeiramente sábia para as compras modernas de todos os dias.",
      questions: [
        { question: "What does the retail industry rely heavily on?", options: ["Seasonal trends", "Selling high-quality leather", "Keeping prices high", "Vintage shops"], correctIndex: 0, explanation: "The industry relies heavily on 'rapidly changing seasonal trends'." },
        { question: "What must consumers consider when buying cheap garments?", options: ["The environmental impact", "The thrill of a bargain", "The seasonal trends", "The vintage shops"], correctIndex: 0, explanation: "We must consider 'the severe, devastating long-term environmental impact of mass-producing millions of cheap, low-quality garments'." },
        { question: "What did the author recently discover?", options: ["A vintage shop with high-quality goods", "A fast fashion store", "A cheap garment factory", "A new shopping mall"], correctIndex: 0, explanation: "They discovered 'a remarkably charming vintage shop... that exclusively sells high-quality, pre-owned leather goods'." },
        { question: "What is presented as a sustainable approach?", options: ["Investing in durable items", "Buying cheap clothes", "Updating wardrobes frequently", "Shopping at the mall"], correctIndex: 0, explanation: "The text concludes 'Investing intelligently in highly durable, timeless items... is undeniably a much more sustainable... approach'." }
      ]
    }
  },
  "profissoes": {
    level1: {
      textEn: "Carefully choosing a proper career path is undoubtedly one of the biggest and most critically important decisions for any young person entering adulthood. Personally, I firmly want to become a dedicated elementary school teacher when I finally graduate because I really, truly enjoy helping energetic young children learn, grow, and discover fascinating new things about the world every day. My older brother, on the other hand, works incredibly hard as a skilled mechanic at a popular local garage downtown, where he expertly fixes broken cars, large trucks, and motorcycles every single day of the week. Next week, my older cousin is feeling very nervous because she has a very demanding and important job interview to become a fully registered pediatric nurse at the main city hospital. Ultimately, it is wonderful that everyone in this busy world has completely different, unique natural talents, diverse personal interests, and highly varied goals for their long-term professional future.",
      textPt: "Escolher cuidadosamente um plano de carreira adequado é, sem dúvida, uma das maiores e mais criticamente importantes decisões para qualquer jovem que entra na idade adulta. Pessoalmente, quero firmemente me tornar um professor dedicado do ensino fundamental quando finalmente me formar porque gosto muito e de verdade de ajudar crianças pequenas e cheias de energia a aprender, crescer e descobrir coisas novas e fascinantes sobre o mundo todos os dias. Meu irmão mais velho, por outro lado, trabalha incrivelmente duro como um mecânico habilidoso em uma popular oficina local no centro da cidade, onde ele conserta com maestria carros quebrados, grandes caminhões e motocicletas todos os dias da semana. Na próxima semana, minha prima mais velha está se sentindo muito nervosa porque tem uma entrevista de emprego muito exigente e importante para se tornar uma enfermeira pediátrica totalmente registrada no principal hospital da cidade. No final das contas, é maravilhoso que todos neste mundo agitado tenham talentos naturais completamente diferentes e únicos, interesses pessoais diversos e objetivos altamente variados para seu futuro profissional de longo prazo.",
      questions: [
        { question: "Why does the author want to be a teacher?", options: ["Because they enjoy helping children learn", "Because it pays a lot of money", "Because they want to work in a hospital", "Because they like fixing cars"], correctIndex: 0, explanation: "They want to be a teacher 'because I really, truly enjoy helping energetic young children learn'." },
        { question: "What is the brother's profession?", options: ["Mechanic", "Teacher", "Nurse", "Driver"], correctIndex: 0, explanation: "The text says 'My older brother... works incredibly hard as a skilled mechanic'." },
        { question: "What is the cousin preparing for?", options: ["A job interview to be a nurse", "A test to become a teacher", "Buying a new car", "Fixing cars at the hospital"], correctIndex: 0, explanation: "The cousin 'has a very demanding and important job interview to become a fully registered pediatric nurse'." },
        { question: "What is the main conclusion of the text?", options: ["Everyone has different talents", "Being a teacher is the best job", "Mechanics make the most money", "It is easy to choose a career"], correctIndex: 0, explanation: "The text concludes: 'everyone in this busy world has completely different, unique natural talents'." }
      ]
    },
    level2: {
      textEn: "The highly competitive, modern corporate workplace is currently evolving incredibly rapidly due to continuous, groundbreaking technological advancements and globalization. Today, demanding multinational employers are actively and desperately seeking highly skilled candidates who can efficiently manage complex international projects and naturally adapt to mastering totally new, intricate software systems as quickly as humanly possible. I recently had the distinct pleasure of conducting an extensive video interview with a brilliantly intelligent candidate hailing from overseas, and their remarkably unique, diverse cultural perspective almost instantly proved to be a great, truly invaluable strategic asset for our entire global marketing team. Additionally, the widespread modern trend of working remotely from home has drastically and permanently changed how we interact daily with our colleagues; instead of enjoying casual, spontaneous office conversations by the water cooler, we now rely almost exclusively on rigidly scheduling formal, structured virtual meetings throughout the day. Ultimately, professional adaptability and mental flexibility are now universally considered absolutely key survival skills in this relentlessly demanding new digital era.",
      textPt: "O ambiente de trabalho corporativo moderno, altamente competitivo, está evoluindo de forma incrivelmente rápida devido aos contínuos e inovadores avanços tecnológicos e à globalização. Hoje, exigentes empregadores multinacionais estão buscando ativa e desesperadamente candidatos altamente qualificados que possam gerenciar com eficiência projetos internacionais complexos e se adaptar naturalmente ao domínio de sistemas de software novos e intrincados o mais rápido humanamente possível. Recentemente, tive o grande prazer de realizar uma extensa entrevista por vídeo com um candidato brilhantemente inteligente vindo do exterior, e sua perspectiva cultural notavelmente única e diversa provou quase instantaneamente ser um recurso estratégico excelente e verdadeiramente inestimável para toda a nossa equipe de marketing global. Além disso, a tendência moderna generalizada de trabalhar remotamente de casa mudou drástica e permanentemente a forma como interagimos diariamente com nossos colegas; em vez de desfrutar de conversas casuais e espontâneas no escritório perto do bebedouro, agora dependemos quase exclusivamente do agendamento rígido de reuniões virtuais formais e estruturadas ao longo do dia. Em última análise, a adaptabilidade profissional e a flexibilidade mental são agora universalmente consideradas habilidades de sobrevivência absolutamente fundamentais nesta nova e implacável era digital.",
      questions: [
        { question: "What skills do employers value in candidates?", options: ["Managing projects and adapting quickly", "Fixing computers", "Working without software", "Traveling overseas"], correctIndex: 0, explanation: "Employers seek candidates who 'can efficiently manage complex international projects and naturally adapt to mastering totally new, intricate software systems'." },
        { question: "Why was the overseas candidate valuable?", options: ["They brought a diverse perspective", "They worked for less money", "They wanted to work remotely", "They avoided virtual meetings"], correctIndex: 0, explanation: "Their 'remarkably unique, diverse cultural perspective almost instantly proved to be a great, truly invaluable strategic asset'." },
        { question: "How has remote work changed employee interactions?", options: ["Employees hold virtual meetings", "Employees never interact", "Employees travel more", "Employees work longer hours"], correctIndex: 0, explanation: "Instead of casual office conversations, 'we now rely almost exclusively on rigidly scheduling formal, structured virtual meetings'." },
        { question: "What is considered a key professional skill?", options: ["Flexibility", "Software engineering", "Interviewing", "Working overseas"], correctIndex: 0, explanation: "The text concludes 'professional adaptability and mental flexibility are now universally considered absolutely key survival skills'." }
      ]
    }
  },
  "lugares": {
    level1: {
      textEn: "Even though the town where I proudly live is quite small and quiet, it actually has many incredibly interesting and remarkably beautiful public places that tourists love to visit. The lively, cobblestone central square has a spectacular, towering water fountain right in the middle where many young children excitedly like to play and splash around in the late, warm afternoon. Right next to the busy, crowded square, there is a wonderfully large, peacefully quiet public library that is completely filled with thousands upon thousands of fascinating, educational books for all ages. On most relaxing Fridays, after school is finally over, I usually go straight to the big, modern movie theater downtown with my best friends to happily watch the latest blockbuster movie releases. The only major, annoying problem with my otherwise perfect town is that the main intercity bus station is located very, very far away from my house, which simply means we always have to frustratingly walk a lot just to get there.",
      textPt: "Embora a cidade onde eu vivo orgulhosamente seja bem pequena e tranquila, na verdade ela tem muitos lugares públicos incrivelmente interessantes e incrivelmente bonitos que os turistas adoram visitar. A animada praça central de paralelepípedos tem uma espetacular e imponente fonte de água bem no meio, onde muitas crianças adoram brincar e se molhar no final da tarde quente. Bem ao lado da praça movimentada e lotada, há uma biblioteca pública maravilhosamente grande e pacificamente silenciosa que é totalmente repleta de milhares e milhares de livros fascinantes e educacionais para todas as idades. Nas sextas-feiras mais relaxantes, depois que as aulas finalmente acabam, costumo ir direto ao grande e moderno cinema do centro da cidade com meus melhores amigos para assistir alegremente aos últimos sucessos de bilheteria. O único problema grande e irritante com minha cidade, que de outra forma seria perfeita, é que a principal rodoviária intermunicipal fica muito, muito longe da minha casa, o que significa simplesmente que sempre temos que andar muito, de forma frustrante, só para chegar lá.",
      questions: [
        { question: "What can be found in the central square?", options: ["A beautiful fountain", "A large bus station", "A movie theater", "Thousands of books"], correctIndex: 0, explanation: "The text mentions 'The lively, cobblestone central square has a spectacular, towering water fountain'." },
        { question: "Where is the large library located?", options: ["Next to the central square", "Far from the house", "Inside the movie theater", "Next to the bus station"], correctIndex: 0, explanation: "The text says 'Right next to the busy, crowded square, there is a wonderfully large, peacefully quiet public library'." },
        { question: "When does the author usually visit the movie theater?", options: ["On Fridays", "Every afternoon", "On weekends", "In the morning"], correctIndex: 0, explanation: "They say 'On most relaxing Fridays... I usually go straight to the big, modern movie theater'." },
        { question: "What is the negative aspect of the town?", options: ["The bus station is very far", "The library doesn't have enough books", "The town is too noisy", "The fountain is broken"], correctIndex: 0, explanation: "The only major, annoying problem is 'that the main intercity bus station is located very, very far away from my house'." }
      ]
    },
    level2: {
      textEn: "Successfully navigating your way through a massive, perpetually busy, and chaotic modern metropolis undeniably requires immense mental patience, sharp situational awareness, and a truly flawless sense of direction. Whenever I find myself traveling to entirely new and unfamiliar destinations, I actively make a conscious effort to never ignore the intricate, breathtaking architectural details of the old historical buildings that proudly line the narrow streets. Just last month, I eagerly visited an incredibly exclusive, highly anticipated contemporary art exhibition downtown that was truly captivating and deeply thought-provoking for days afterward. Unfortunately, to finally get there on time, I had to briskly walk several exhausting miles completely around the confusing, maze-like city center simply because my domestic flight was severely delayed and the public trains were hopelessly broken. While thoroughly exploring public urban places entirely on foot is undeniably physically tiring and demanding on the feet, it is also incredibly rewarding, mentally stimulating, and profoundly eye-opening to properly absorb the unique local culture.",
      textPt: "Navegar com sucesso por uma metrópole moderna enorme, perpetuamente movimentada e caótica exige inegavelmente imensa paciência mental, grande consciência situacional e um senso de direção verdadeiramente impecável. Sempre que me vejo viajando para destinos totalmente novos e desconhecidos, faço ativamente um esforço consciente para nunca ignorar os detalhes arquitetônicos intrincados e deslumbrantes dos antigos edifícios históricos que alinham orgulhosamente as ruas estreitas. Apenas no mês passado, visitei ansiosamente uma exposição de arte contemporânea incrivelmente exclusiva e altamente antecipada no centro da cidade, que foi verdadeiramente cativante e profundamente instigante por dias a fio. Infelizmente, para finalmente chegar lá a tempo, tive que caminhar apressadamente várias milhas exaustivas completamente ao redor do centro da cidade, que parecia um labirinto confuso, simplesmente porque meu voo doméstico estava severamente atrasado e os trens públicos estavam irremediavelmente quebrados. Embora explorar minuciosamente espaços urbanos públicos inteiramente a pé seja inegavelmente cansativo fisicamente e exigente para os pés, é também incrivelmente gratificante, mentalmente estimulante e profundamente revelador para absorver adequadamente a cultura local única.",
      questions: [
        { question: "What does navigating a busy metropolis require?", options: ["Patience", "A fast car", "Living downtown", "Taking a flight"], correctIndex: 0, explanation: "Navigating a busy metropolis requires 'immense mental patience, sharp situational awareness, and a truly flawless sense of direction'." },
        { question: "What does the author pay attention to while traveling?", options: ["Architectural details of historical buildings", "The delays of trains", "The cost of flights", "The number of miles they walk"], correctIndex: 0, explanation: "They try not to ignore 'the intricate, breathtaking architectural details of the old historical buildings'." },
        { question: "Why did the author walk miles around the city center?", options: ["Because the flight was delayed", "Because they wanted to exercise", "Because they couldn't afford a taxi", "Because the exhibition was closed"], correctIndex: 0, explanation: "They walked miles 'simply because my domestic flight was severely delayed and the public trains were hopelessly broken'." },
        { question: "How does the author describe exploring on foot?", options: ["Tiring, but rewarding", "A waste of time", "Very fast", "Boring and difficult"], correctIndex: 0, explanation: "They state it is 'ineniably physically tiring... it is also incredibly rewarding'." }
      ]
    }
  },
  "animais": {
    level1: {
      textEn: "Animals are truly fascinating, incredibly diverse, and absolutely wonderful creatures that beautifully share our giant planet with us. My absolute favorite animal in the entire world is the domestic dog because it is universally known to be very friendly, highly loyal, and fiercely protective of its loving human family. In fact, my closest next-door neighbor actually has a big, extremely fluffy brown dog that loves to excitedly bark very loudly whenever the tired postman arrives at the front gate every morning. Conversely, some people much prefer having cats as indoor pets because they are generally very quiet, highly independent, and extremely clean animals that rarely cause any trouble. Last summer during our fun family vacation, we drove to the large city zoo and were amazed to see magnificent roaring lions, giant gray elephants spraying water, and funny little monkeys playfully jumping high up in the tall green trees all afternoon.",
      textPt: "Os animais são criaturas verdadeiramente fascinantes, incrivelmente diversas e absolutamente maravilhosas que compartilham lindamente nosso planeta gigante conosco. Meu animal favorito no mundo inteiro é o cão doméstico, porque é universalmente conhecido por ser muito amigável, altamente leal e ferozmente protetor de sua amorosa família humana. De fato, meu vizinho mais próximo tem um cachorro marrom grande e extremamente fofo que adora latir muito alto e animadamente sempre que o carteiro cansado chega ao portão da frente todas as manhãs. Por outro lado, algumas pessoas preferem muito mais ter gatos como animais de estimação de interior porque geralmente são animais muito quietos, altamente independentes e extremamente limpos, que raramente causam problemas. No verão passado, durante nossas divertidas férias em família, dirigimos até o grande zoológico da cidade e ficamos maravilhados ao ver leões magníficos rugindo, elefantes cinzentos gigantes esguichando água e macaquinhos engraçados pulando de brincadeira no alto das grandes árvores verdes a tarde toda.",
      questions: [
        { question: "Why does the author favor dogs?", options: ["Because they are friendly", "Because they are quiet", "Because they jump in trees", "Because they bark a lot"], correctIndex: 0, explanation: "The author favors dogs 'because it is universally known to be very friendly, highly loyal, and fiercely protective'." },
        { question: "What does the neighbor's dog like to do?", options: ["Bark", "Sleep all day", "Jump in trees", "Chase cats"], correctIndex: 0, explanation: "The neighbor has a dog that 'loves to excitedly bark very loudly'." },
        { question: "Why do some people prefer cats?", options: ["Because they are quiet", "Because they are friendly", "Because they are big", "Because they like to bark"], correctIndex: 0, explanation: "People prefer cats 'because they are generally very quiet, highly independent, and extremely clean'." },
        { question: "Where did they see lions and elephants?", options: ["At the zoo", "In the neighbor's yard", "At the park", "In the forest"], correctIndex: 0, explanation: "They 'drove to the large city zoo and were amazed to see magnificent roaring lions, giant gray elephants'." }
      ]
    },
    level2: {
      textEn: "Global wildlife conservation is an absolutely essential endeavor for successfully maintaining the delicate, interconnected balance of our planet's incredibly rich and diverse biodiversity. Unfortunately, ever since the aggressive dawn of the global industrial revolution, the grim, heartbreaking timeline of global species extinction has accelerated quite alarmingly across absolutely all continents and oceans. Just last month, I had the distinct privilege of visiting a massive, state-of-the-art coastal aquarium that focuses extensively and passionately on rescuing, treating, and rehabilitating severely injured marine animals before returning them to the wild. The knowledgeable educational guides there strongly emphasized repeatedly that continuously educating the ignorant general public about these majestic, deeply vulnerable creatures is truly the critical, fundamental first step toward ultimately saving them from tragic, permanent extinction in our lifetimes.",
      textPt: "A conservação global da vida selvagem é um esforço absolutamente essencial para manter com sucesso o equilíbrio delicado e interconectado da biodiversidade incrivelmente rica e diversificada do nosso planeta. Infelizmente, desde o alvorecer agressivo da revolução industrial global, a linha do tempo sombria e de partir o coração da extinção de espécies globais acelerou de forma bastante alarmante em absolutamente todos os continentes e oceanos. Apenas no mês passado, tive o distinto privilégio de visitar um enorme aquário costeiro de última geração que se concentra extensa e apaixonadamente no resgate, tratamento e reabilitação de animais marinhos gravemente feridos antes de devolvê-los à natureza. Os guias educacionais experientes lá enfatizaram fortemente e repetidamente que educar continuamente o público em geral ignorante sobre essas criaturas majestosas e profundamente vulneráveis é verdadeiramente o primeiro passo crítico e fundamental para, em última análise, salvá-las da trágica e permanente extinção em nossas vidas.",
      questions: [
        { question: "What is the primary reason for wildlife conservation?", options: ["To maintain biodiversity", "To build more aquariums", "To prevent hunting", "To accelerate extinction"], correctIndex: 0, explanation: "It is 'an absolutely essential endeavor for successfully maintaining the delicate, interconnected balance of our planet's incredibly rich and diverse biodiversity'." },
        { question: "What has happened since the industrial revolution?", options: ["Species extinction has accelerated alarmingly", "Extinction has stopped", "Biodiversity has increased", "Marine animals were rescued"], correctIndex: 0, explanation: "Since then, 'the grim, heartbreaking timeline of global species extinction has accelerated quite alarmingly'." },
        { question: "What was the focus of the aquarium?", options: ["Rescuing marine animals", "Training sharks to hunt", "Breeding lions", "Selling exotic fish"], correctIndex: 0, explanation: "The aquarium 'focuses extensively and passionately on rescuing, treating, and rehabilitating severely injured marine animals'." },
        { question: "What is the first step toward saving these creatures?", options: ["Educating the public", "Stopping the industrial revolution", "Closing aquariums", "Feeding them more"], correctIndex: 0, explanation: "'Educating the ignorant general public about these majestic, deeply vulnerable creatures is truly the critical, fundamental first step'." }
      ]
    }
  },
  "culinaria": {
    level1: {
      textEn: "Knowing precisely how to cook your own healthy, delicious meals is a very useful and incredibly practical daily skill that absolutely everyone should eventually learn. On most busy weekday mornings, I usually choose to quickly boil a couple of fresh farm eggs and gently fry some deliciously crispy bacon in a hot pan to ensure I have a very hearty, energy-filled breakfast. Later in the warm afternoon, if you passionately want to make a healthy, crunchy green salad, you have to carefully chop various fresh vegetables like juicy red tomatoes and crisp green cucumbers using a very sharp, professional kitchen knife. Meanwhile, my wonderfully talented mother always likes to lovingly bake incredibly delicious, sweet chocolate cakes in the hot oven whenever we have special family guests over. Over the years, I have confidently learned that strictly following a detailed, well-written recipe really helps you accurately measure and perfectly mix all the necessary ingredients without making a huge mess in the kitchen.",
      textPt: "Saber precisamente como cozinhar suas próprias refeições saudáveis e deliciosas é uma habilidade diária muito útil e incrivelmente prática que absolutamente todos deveriam aprender eventualmente. Na maioria das manhãs agitadas de dias de semana, eu geralmente escolho ferver rapidamente alguns ovos frescos da fazenda e fritar suavemente um pouco de bacon deliciosamente crocante em uma panela quente para garantir um café da manhã muito farto e cheio de energia. Mais tarde na tarde quente, se você deseja apaixonadamente fazer uma salada verde crocante e saudável, precisa picar com cuidado vários vegetais frescos, como tomates vermelhos suculentos e pepinos verdes crocantes, usando uma faca de cozinha profissional muito afiada. Enquanto isso, minha mãe maravilhosamente talentosa sempre gosta de assar com amor bolos de chocolate doces e incrivelmente deliciosos no forno quente sempre que temos convidados especiais em família. Ao longo dos anos, aprendi com confiança que seguir estritamente uma receita detalhada e bem escrita realmente ajuda a medir com precisão e misturar perfeitamente todos os ingredientes necessários sem fazer uma bagunça enorme na cozinha.",
      questions: [
        { question: "What does the author usually make for breakfast?", options: ["Boiled eggs and bacon", "Chocolate cakes", "A fresh salad", "Cereal and milk"], correctIndex: 0, explanation: "They usually 'choose to quickly boil a couple of fresh farm eggs and gently fry some deliciously crispy bacon'." },
        { question: "What tool is used to chop vegetables?", options: ["A sharp knife", "A spoon", "An oven", "A fork"], correctIndex: 0, explanation: "You chop fresh vegetables 'using a very sharp, professional kitchen knife'." },
        { question: "What does the mother like to bake?", options: ["Chocolate cakes", "Bread", "Cookies", "Pizza"], correctIndex: 0, explanation: "The mother 'always likes to lovingly bake incredibly delicious, sweet chocolate cakes'." },
        { question: "Why is following a recipe helpful?", options: ["It helps mix ingredients perfectly", "It makes cooking faster", "It cleans the kitchen", "It is required by law"], correctIndex: 0, explanation: "Following a written recipe 'really helps you accurately measure and perfectly mix all the necessary ingredients'." }
      ]
    },
    level2: {
      textEn: "Genuinely mastering the highly advanced, intricate culinary arts requires not only innate, natural raw talent but also immense, monk-like patience and seemingly endless, fearless flavor experimentation over many long years. A truly great, highly respected world-class chef always knows exactly how to perfectly balance conflicting, powerful sweet, salty, and incredibly spicy flavor profiles within a single, cohesive, mouth-watering dish. Yesterday evening, feeling quite adventurous, I bravely attempted a highly complex, notoriously difficult gourmet recipe that involved skillfully pouring a rich, delicate red wine sauce over perfectly grilled, farm-raised organic chicken. Constantly tasting the hot food while you are actively cooking is widely considered incrdibly important by all experts, as it guarantees that the subtle, nuanced seasoning is absolutely just right before it ever leaves the kitchen. Finally, creatively and meticulously presenting the beautifully arranged food on a perfectly warm, pristine white plate is also universally considered a crucial, non-negotiable aspect of the modern fine dining experience.",
      textPt: "Dominar genuinamente as artes culinárias altamente avançadas e intrincadas requer não apenas um talento natural inato, mas também uma imensa paciência de monge e uma experimentação destemida e aparentemente interminável de sabores ao longo de muitos anos. Um chef verdadeiramente grande e altamente respeitado de classe mundial sempre sabe exatamente como equilibrar perfeitamente perfis de sabores conflitantes e poderosos: doces, salgados e incrivelmente picantes em um único prato coeso e de dar água na boca. Ontem à noite, sentindo-me bastante aventureiro, tentei corajosamente uma receita gourmet altamente complexa e notoriamente difícil que envolvia derramar habilmente um molho rico e delicado de vinho tinto sobre frango orgânico perfeitamente grelhado, criado em fazenda. Provar constantemente a comida quente enquanto se está cozinhando ativamente é amplamente considerado incrivelmente importante por todos os especialistas, pois garante que o tempero sutil e cheio de nuances esteja absolutamente perfeito antes de sair da cozinha. Por fim, apresentar a comida lindamente arranjada, de forma criativa e meticulosa, em um prato branco imaculado e perfeitamente aquecido, também é universalmente considerado um aspecto crucial e inegociável da experiência gastronômica moderna.",
      questions: [
        { question: "What does mastering the culinary arts require?", options: ["Patience and experimentation", "A sharp knife and an oven", "Only expensive ingredients", "Cooking very fast"], correctIndex: 0, explanation: "It requires 'immense, monk-like patience and seemingly endless, fearless flavor experimentation'." },
        { question: "What should a great chef know how to balance?", options: ["Sweet, salty, and spicy flavors", "Water and oil", "Meat and vegetables", "Time and money"], correctIndex: 0, explanation: "A great chef knows how to balance 'sweet, salty, and incredibly spicy flavor profiles'." },
        { question: "Why is tasting the food while cooking important?", options: ["It ensures the seasoning is just right", "It makes you less hungry", "It cools down the food", "It is a rule in the recipe"], correctIndex: 0, explanation: "Tasting the hot food 'guarantees that the subtle, nuanced seasoning is absolutely just right before it ever leaves the kitchen'." },
        { question: "What is also considered crucial in cooking?", options: ["Presenting the food beautifully on a plate", "Washing the dishes immediately", "Buying a new oven", "Using a lot of salt"], correctIndex: 0, explanation: "'Creatively and meticulously presenting the beautifully arranged food on a perfectly warm... plate is also universally considered a crucial... aspect'." }
      ]
    }
  },
  "tecnologia": {
    level1: {
      textEn: "In my increasingly busy daily life, I undeniably rely very heavily on my powerful personal smartphone and ultra-lightweight laptop to rapidly accomplish almost every single necessary task, from schoolwork to managing my bank accounts. In order to safely and privately access the vast internet and securely read my important personal emails, I always make sure to carefully type a highly secret, incredibly complicated alphanumeric password. During my limited free time on weekends, I often thoroughly enjoy downloading innovative new entertainment apps and exciting, brain-teasing puzzle games straight from the digital app store. Whenever the small screen prominently indicates that the device's battery is dangerously running low, I quickly grab a highly compatible, fast-charging cable and plug it firmly into the nearby wall socket. Thankfully, modern smart devices are brilliantly designed to be exceptionally user-friendly; for instance, it is very easy for anyone to type extremely quickly on the responsive digital keyboard and comfortably look at the brilliantly bright, stunningly high-resolution glass screen without hurting their eyes.",
      textPt: "Na minha vida diária cada vez mais ocupada, dependo inegavelmente e muito do meu poderoso smartphone pessoal e laptop ultraleve para realizar rapidamente quase todas as tarefas necessárias, desde o trabalho escolar até o gerenciamento de minhas contas bancárias. Para acessar a vasta internet de forma segura e privada e ler meus e-mails pessoais importantes com segurança, sempre me certifico de digitar cuidadosamente uma senha alfanumérica altamente secreta e incrivelmente complicada. Durante meu limitado tempo livre nos fins de semana, costumo gostar muito de baixar novos aplicativos de entretenimento inovadores e emocionantes jogos de quebra-cabeça direto da loja de aplicativos digitais. Sempre que a tela pequena indica de forma proeminente que a bateria do dispositivo está perigosamente fraca, pego rapidamente um cabo de carregamento rápido altamente compatível e conecto-o firmemente à tomada de parede mais próxima. Felizmente, os dispositivos inteligentes modernos são brilhantemente projetados para serem excepcionalmente fáceis de usar; por exemplo, é muito fácil para qualquer pessoa digitar extremamente rápido no teclado digital responsivo e olhar confortavelmente para a tela de vidro incrivelmente brilhante e de alta resolução sem machucar os olhos.",
      questions: [
        { question: "What devices does the author use every day?", options: ["Smartphone and laptop", "Television and radio", "Tablet and smartwatch", "Camera and printer"], correctIndex: 0, explanation: "The text states 'I undeniably rely very heavily on my powerful personal smartphone and ultra-lightweight laptop'." },
        { question: "What is needed to use the internet?", options: ["A secret password", "A new app", "A charger", "A printer"], correctIndex: 0, explanation: "They say 'In order to safely and privately access the vast internet... I always make sure to carefully type a highly secret, incredibly complicated alphanumeric password'." },
        { question: "What does the author often download?", options: ["New apps and games", "Movies and music", "Books and photos", "Viruses"], correctIndex: 0, explanation: "They often enjoy 'downloading innovative new entertainment apps and exciting, brain-teasing puzzle games'." },
        { question: "What do you use when the battery is low?", options: ["A charger", "A keyboard", "A screen", "A password"], correctIndex: 0, explanation: "They state 'Whenever the small screen prominently indicates that the device's battery is dangerously running low, I quickly grab a highly compatible, fast-charging cable'." }
      ]
    },
    level2: {
      textEn: "The incredibly rapid and widespread global adoption of advanced cloud computing technology has fundamentally, totally, and irreversibly revolutionized exactly how modern, massive multinational businesses and everyday individuals securely store their priceless digital data. Instead of precariously keeping all your vulnerable, irreplaceable files on a single, fragile, easily broken local hard drive, you can now seamlessly and instantly upload absolutely everything to a highly secure, heavily encrypted remote server located thousands of miles away. This amazing, cutting-edge capability makes it incredibly easy and intuitive to logically organize tens of thousands of complex files into neat, structured digital folders and instantly access them from absolutely any internet-connected smart device anywhere in the world. However, despite these tremendous, game-changing benefits, you must always remain highly vigilant and extremely careful with deceptively disguised malicious phishing links that could potentially steal your highly sensitive private financial data in mere seconds. Therefore, regularly and automatically backing up your important files and consistently updating your device's operating software is universally considered absolutely essential for maintaining robust, impenetrable cybersecurity.",
      textPt: "A incrivelmente rápida e generalizada adoção global da tecnologia avançada de computação em nuvem revolucionou de forma fundamental, total e irreversível exatamente como empresas multinacionais modernas e massivas e indivíduos comuns armazenam de forma segura seus preciosos dados digitais. Em vez de manter precariamente todos os seus arquivos vulneráveis e insubstituíveis em um único disco rígido local frágil e facilmente quebrável, agora você pode enviar perfeitamente e instantaneamente absolutamente tudo para um servidor remoto altamente seguro e fortemente criptografado localizado a milhares de quilômetros de distância. Esse recurso incrível e de ponta torna incrivelmente fácil e intuitivo organizar logicamente dezenas de milhares de arquivos complexos em pastas digitais organizadas e estruturadas, acessando-os instantaneamente de absolutamente qualquer dispositivo inteligente conectado à Internet em qualquer lugar do mundo. No entanto, apesar desses benefícios tremendos e transformadores, você deve sempre permanecer altamente vigilante e extremamente cuidadoso com links de phishing maliciosos e enganosamente disfarçados que poderiam roubar seus dados financeiros privados altamente sensíveis em meros segundos. Portanto, o backup regular e automático de seus arquivos importantes e a atualização consistente do software operacional de seu dispositivo são universalmente considerados absolutamente essenciais para manter uma segurança cibernética robusta e impenetrável.",
      questions: [
        { question: "How has cloud computing changed data storage?", options: ["You can upload files to a secure server", "You must keep files on a local hard drive", "It deleted all digital folders", "It made passwords unnecessary"], correctIndex: 0, explanation: "You can 'seamlessly and instantly upload absolutely everything to a highly secure, heavily encrypted remote server'." },
        { question: "What is an advantage of using digital folders in the cloud?", options: ["Accessing files from any device", "Avoiding software updates", "Increasing battery life", "Listening to music offline"], correctIndex: 0, explanation: "It makes it easy to 'instantly access them from absolutely any internet-connected smart device anywhere in the world'." },
        { question: "What danger should users be careful about?", options: ["Malicious links that could steal data", "Uploading too many photos", "Forgetting the charger", "Organizing files too often"], correctIndex: 0, explanation: "You must be careful with 'deceptively disguised malicious phishing links that could potentially steal your highly sensitive private financial data'." },
        { question: "What is considered essential for data security?", options: ["Regularly backing up and updating software", "Sharing passwords", "Using a local hard drive", "Clicking on all links"], correctIndex: 0, explanation: "'Regularly and automatically backing up your important files and consistently updating your device's operating software is universally considered absolutely essential'." }
      ]
    }
  },
  "redes-sociais": {
    level1: {
      textEn: "Using a variety of popular social media applications on my smart phone is definitely a remarkably fun, incredibly fast, and very convenient way to stay closely and constantly connected with all my beloved friends and distant family members across the globe. I really, truly enjoy taking the necessary time to edit and post beautiful, bright, high-resolution photos from my exciting weekend camping trips and happily share them on my public digital profile page for absolutely everyone to see and admire. When I casually scroll down through my seemingly endless daily news feed during my quick lunch break at work, I can easily leave a nice, highly supportive comment or simply tap the screen twice to instantly like the latest stunning pictures uploaded by my closest friends. Additionally, I recently learned that actively using a very popular, trending hashtag in all your creative posts significantly and effectively helps other interested people around the entire world rapidly find and enthusiastically join lively conversations about highly interesting, current trending topics.",
      textPt: "Usar uma variedade de aplicativos populares de mídia social no meu smartphone é, sem dúvida, uma maneira notavelmente divertida, incrivelmente rápida e muito conveniente de me manter conectado de perto e constantemente com todos os meus amados amigos e familiares distantes em todo o mundo. Eu realmente gosto de reservar o tempo necessário para editar e postar fotos lindas, brilhantes e de alta resolução das minhas emocionantes viagens de acampamento de fim de semana e compartilhá-las alegremente em minha página de perfil digital público para que absolutamente todos possam ver e admirar. Quando rolo casualmente meu feed de notícias diário aparentemente infinito durante minha rápida pausa para o almoço no trabalho, posso facilmente deixar um comentário agradável e de grande apoio ou simplesmente tocar na tela duas vezes para curtir instantaneamente as fotos impressionantes mais recentes carregadas por meus amigos mais próximos. Além disso, aprendi recentemente que o uso ativo de uma hashtag de tendência muito popular em todas as suas postagens criativas ajuda significativa e efetivamente outras pessoas interessadas em todo o mundo a encontrar rapidamente e a participar com entusiasmo de conversas animadas sobre tópicos atuais de tendência altamente interessantes.",
      questions: [
        { question: "What is social media used for in the text?", options: ["To connect with friends", "To download games", "To buy new clothes", "To watch movies"], correctIndex: 0, explanation: "It is a 'remarkably fun, incredibly fast, and very convenient way to stay closely and constantly connected with all my beloved friends'." },
        { question: "Where does the author share photos?", options: ["On their profile", "In a private message", "In an email", "On a website"], correctIndex: 0, explanation: "They 'happily share them on my public digital profile page'." },
        { question: "What can the author do while scrolling the feed?", options: ["Leave a comment or like pictures", "Delete old photos", "Change their password", "Call their friends"], correctIndex: 0, explanation: "They can 'easily leave a nice, highly supportive comment or simply tap the screen twice to instantly like the latest stunning pictures'." },
        { question: "What is the purpose of a hashtag?", options: ["To help people find interesting topics", "To protect your password", "To charge your phone", "To block a follower"], correctIndex: 0, explanation: "A popular hashtag 'significantly and effectively helps other interested people... find and enthusiastically join lively conversations about highly interesting, current trending topics'." }
      ]
    },
    level2: {
      textEn: "In today's highly competitive, fiercely cutthroat global corporate landscape, modern digital marketing strategies rely exceptionally heavily on unbelievably complex, completely opaque, and constantly changing artificial intelligence algorithms embedded within social media platforms to effectively reach millions of potential consumers. Popular, highly ambitious internet influencers continuously and obsessively attempt to strategically create viral, intensely eye-catching, and emotionally provocative short videos, blindly hoping to spontaneously gain hundreds of thousands of new, fiercely loyal followers almost overnight. Furthermore, the brilliant, highly manipulative psychological marketing tactic of deliberately posting an engaging, exclusive video story that permanently and irreversibly disappears in exactly 24 hours effectively creates a powerful, irresistible sense of urgency and fear of missing out among the captivated audience. Given exactly how much highly sensitive behavioral data these massive tech platforms ruthlessly collect daily, it is incredibly, absolutely important that users take the necessary time to rigorously adjust their intricate account privacy settings to proactively ensure their deeply sensitive personal data is fiercely protected from aggressive, completely unwanted corporate surveillance and access.",
      textPt: "No cenário corporativo global altamente competitivo e ferozmente cruel de hoje, as estratégias modernas de marketing digital dependem excepcionalmente forte de algoritmos de inteligência artificial incrivelmente complexos, completamente opacos e em constante mudança, incorporados às plataformas de mídia social, para alcançar efetivamente milhões de consumidores em potencial. Influenciadores populares da internet, altamente ambiciosos, tentam contínua e obsessivamente criar de forma estratégica vídeos curtos virais, intensamente atraentes e emocionalmente provocantes, esperando cegamente ganhar espontaneamente centenas de milhares de novos seguidores ferozmente leais, quase da noite para o dia. Além disso, a brilhante e altamente manipuladora tática psicológica de marketing de postar deliberadamente um story de vídeo envolvente e exclusivo que desaparece de forma permanente e irreversível em exatamente 24 horas cria efetivamente uma poderosa e irresistível sensação de urgência e medo de perder entre o público cativado. Considerando exatamente a quantidade de dados comportamentais altamente sensíveis que essas gigantescas plataformas de tecnologia coletam implacavelmente diariamente, é incrível e absolutamente importante que os usuários reservem o tempo necessário para ajustar rigorosamente suas intrincadas configurações de privacidade de conta para garantir proativamente que seus dados pessoais profundamente sensíveis sejam ferozmente protegidos da vigilância e do acesso corporativo agressivo e completamente indesejado.",
      questions: [
        { question: "What does digital marketing rely on?", options: ["Social media algorithms", "Private messages", "Hashtags only", "Local hard drives"], correctIndex: 0, explanation: "It relies 'exceptionally heavily on unbelievably complex... artificial intelligence algorithms embedded within social media platforms'." },
        { question: "What is the goal of creating a viral video?", options: ["To gain thousands of new followers", "To delete the profile", "To hide personal data", "To adjust privacy settings"], correctIndex: 0, explanation: "They hope 'to spontaneously gain hundreds of thousands of new, fiercely loyal followers almost overnight'." },
        { question: "What creates a sense of urgency on social platforms?", options: ["Posting a story that disappears in 24 hours", "Uploading a photo to the feed", "Leaving a short comment", "Following many people"], correctIndex: 0, explanation: "Posting an 'engaging, exclusive video story that permanently and irreversibly disappears in exactly 24 hours effectively creates a powerful... sense of urgency'." },
        { question: "Why should you adjust your privacy settings?", options: ["To protect personal data from unwanted access", "To get more followers", "To make a video go viral", "To see more ads"], correctIndex: 0, explanation: "To proactively ensure 'their deeply sensitive personal data is fiercely protected from aggressive, completely unwanted corporate surveillance'." }
      ]
    }
  }
};

function injectData(filePath) {
  let content = fs.readFileSync(filePath, 'utf8');

  for (const [id, reading] of Object.entries(data)) {
    const scenarioStart = content.indexOf(`id: "${id}"`);
    if (scenarioStart === -1) continue;

    let nextId = content.indexOf('id: "', scenarioStart + 10);
    if (nextId === -1) nextId = content.length;
    let section = content.slice(scenarioStart, nextId);

    const readingStr = 'reading: ' + JSON.stringify(reading, null, 6);
    const readingStart = section.indexOf('    reading: {');
    const vocabStart = section.indexOf('    vocabulary: [');
    
    if (readingStart !== -1 && vocabStart !== -1 && vocabStart > readingStart) {
      section = section.slice(0, readingStart) + '    ' + readingStr + ',\n' + section.slice(vocabStart);
    }

    content = content.slice(0, scenarioStart) + section + content.slice(nextId);
  }

  fs.writeFileSync(filePath, content);
}

injectData('./data/scenarios2.ts');
console.log("Injected SUPER Extended Reading into scenarios2.ts with safer AST logic");
